### PR TITLE
[TRAFODION-2003]Rename to be with the prefix Traf

### PR DESCRIPTION
**Pull request by kevinxu021**

### CODE REVIEW

**Comment by kevinxu021** [comment]
jenkins, retest

**Comment by arvind-narain** [comment]
Thanks for the change Kevin. I looked at the build failures. Some hints/steps for the same:

Following link shows the places where HPT4DataSource is being used. 
https://github.com/apache/incubator-trafodion/search?utf8=%E2%9C%93&q=HPT4DataSource

As you notice dcs/util /JdbcT4Util.java  needs to be touched, along with the documentation in accessing.doc – You did touch the same file in rest/util. Maybe these files didn't get added in the commit ?

Also it would be a good idea to inform users on dev/user list of this change since applications using the datasource concept need to be modified.

If you need to look at the build failures - follow the links  from the test failure:
https://jenkins.esgyn.com/job/Check-PR-master/732/

Let’s say we need to check on the debug failure - click on the same:
https://jenkins.esgyn.com/job/build-master-release/859/

Click on Console Output :
https://jenkins.esgyn.com/job/build-master-release/859/console

Click on Detailed logs :
http://traf-testlogs.esgyn.com/PullReq/491/732/build-master-release/

Click on Make.log
http://traf-testlogs.esgyn.com/PullReq/491/732/build-master-release/Make.log

Search for “***” and look for errors before this page.

[ERROR] /home/jenkins/workspace/build-master-release/trafodion/dcs/src/main/java/org/trafodion/dcs/util/JdbcT4Util.java:[53,28] error: cannot find symbol  ##(DCS)
[ERROR] package org.trafodion.jdbc.t4  ##(DCS)

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Comment by selvaganesang** [comment]
It might be good to change the URL too. jdbc:t4jdbc: URL is quit generic.
We might need to have trafodion in the URL.



Selva



*From:* asfgit [mailto:notifications@github.com]
*Sent:* Tuesday, May 24, 2016 9:35 AM
*To:* apache/incubator-trafodion <incubator-trafodion@noreply.github.com>
*Subject:* Re: [apache/incubator-trafodion] [TRAFODION-2003]Rename to be
with the prefix Traf (#491)



Merged #491 <https://github.com/apache/incubator-trafodion/pull/491>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/apache/incubator-trafodion/pull/491#event-670599141>

**Comment by arvind-narain** [comment]
Thanks Kevin. 
Also do please remember to 
1. change the documentation in:
 docs/jdbct4ref_guide/src/asciidoc/_chapters/accessing.adoc 
2. send out an email to user community regarding the change related to datasource.

**Comment by venkat1m** [comment]
+ 1 for adding trafodion to jdbc URL.



“jdbc:trafodion:t4:” or “jdbc:trafodion:t2:”



Venkat



*From:* selvaganesang [mailto:notifications@github.com]
*Sent:* Tuesday, May 24, 2016 11:23 AM
*To:* apache/incubator-trafodion <incubator-trafodion@noreply.github.com>
*Subject:* Re: [apache/incubator-trafodion] [TRAFODION-2003]Rename to be
with the prefix Traf (#491)



It might be good to change the URL too. jdbc:t4jdbc: URL is quit generic.
We might need to have trafodion in the URL.



Selva



*From:* asfgit [mailto:notifications@github.com <notifications@github.com>]
*Sent:* Tuesday, May 24, 2016 9:35 AM
*To:* apache/incubator-trafodion <incubator-trafodion@noreply.github.com>
*Subject:* Re: [apache/incubator-trafodion] [TRAFODION-2003]Rename to be
with the prefix Traf (#491)



Merged #491 <https://github.com/apache/incubator-trafodion/pull/491>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/apache/incubator-trafodion/pull/491#event-670599141>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/apache/incubator-trafodion/pull/491#issuecomment-221353197>[image:
https://github.com/notifications/beacon/ALhvZmh94vIUJ0pAEPHfnUuOeBQvK0VHks5qE0ILgaJpZM4Ih8bF.gif]

**Pull request merged**
