### PR TITLE
[TRAFODION-2462] TRAFCI gui installer does not work

### PR DESCRIPTION
**Pull request by AlexPeng19**
fix jira 2462

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
If you put [TRAFODION-2462] into the title for your pull request, then the JIRA will automatically be updated. (As it is we would have to hand-update it.)

**Comment by DaveBirdsall** [comment]
I took a look at the JIRA. It lists a number of issues. I'm guessing this change addresses only some of them. Could you comment on which issues you think are fixed with this change?

**Comment by AlexPeng19** [comment]
@DaveBirdsall ok, i added comment under the jira, please check.

**Comment by AlexPeng19** [comment]
sorry, i did not give much infomation in the git log. the pull are expected to fix two issues, first one, the trafci gui installer, second is : trafci multi line extra SQL> prompt issue. while input multi line, it will print as +>SQL>, it should be +>.

**Pull request merged**
