### PR TITLE
[TRAFODION-1752] JVM goes out-of-memory for hundreds of upsert statem…

### PR DESCRIPTION
**Pull request by selvaganesang**
…ent in one session

HTableClient object was not getting released under certain conditions in batch get operation.
Fixed the code to release the object under these conditions.

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good. Does this bug occur in any of the other HBase tcbs?

**Comment by selvaganesang** [comment]
It is possible that it might happen with other tcbs too. It is important that the HTableClient is released from the JNI/ executor side for get, batch get and scan operations. The HTableClient object is released on the java side in case of Put and Delete operations for non-async operations. I will go through the code where getRowOpen, getRowsOpen and scanOpen is being called and fix it in those places too

**Comment by DaveBirdsall** [comment]
Just checking: Selva, are you planning any more changes? If not, I think this change is ready to commit.

**Comment by selvaganesang** [comment]
Yes. I have observed there is a possibility of leaking HTableClient objects in other places. I will fix them too.

**Comment by DaveBirdsall** [comment]
Looks good to me. I might have chosen a different name for "DONE_WITH_CLOSE". To my ears, this suggests that we are done closing, but from the code I see that it means, "done, except we still need to do a close". "DONE_EXCEPT_CLOSE" might have been a little better. But I don't think this should hold back the commit.

**Comment by selvaganesang** [comment]
I can change it into CLOSE_AND_DONE if needed because this is what this step does. Isn't?

**Comment by DaveBirdsall** [comment]
That sounds good.

**Comment by DaveBirdsall** [comment]
Looks good to me. Let's ship this puppy.

**Comment by selvaganesang** [comment]
Can you please commit this tomorrow if you don't hear any more review comments

**Comment by DaveBirdsall** [comment]
Yes



*From:* selvaganesang [mailto:notifications@github.com]
*Sent:* Wednesday, January 20, 2016 2:23 PM
*To:* apache/incubator-trafodion <incubator-trafodion@noreply.github.com>
*Cc:* DaveBirdsall <dave.birdsall@esgyn.com>
*Subject:* Re: [incubator-trafodion] [TRAFODION-1752] JVM goes
out-of-memory for hundreds of upsert statem… (#263)



Can you please commit this tomorrow if you don't hear any more review
comments

—
Reply to this email directly or view it on GitHub
<https://github.com/apache/incubator-trafodion/pull/263#issuecomment-173381058>
.

**Pull request merged**
