### PR TITLE
TRAFODION-2788 - jdbc does not implement ClinetInfo related api

### PR DESCRIPTION
**Pull request by gpj1987**
when use jdbc there is not implement with setClientInfo and getClientInfo

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, ok to test

**Comment by selvaganesang** [comment]
Should the standard client info properties sent to server and made visible in DCS Web GUI too

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Comment by arvind-narain** [comment]
Thanks for these enhancements. Could you please check how connections are handled in other related tests and do the same in TestClientInfo.java? Currently connections are not getting closed, hence other tests are failing since there are no available servers.

**Comment by gpj1987** [comment]
thanks, for the comments, I will try to change it to make it visible in DCS Web GUI

**Comment by selvaganesang** [comment]
I will merge this PR. You can open a different PR to take care of the requested enhancements

**Pull request merged**
