### PR TITLE
[TRAFODION-17]Check the closed status of statement

### PR DESCRIPTION
**Pull request by xwq**
Check the closed statement object status failed, always get false.

Change-Id: Ifa881efffb9bce01af155d78eea4d123466910bb

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
jenkins, add user

**Comment by arvind-narain** [comment]
Change looks good to me.

**Comment by sureshsubbiah** [comment]
jenkins, retest

**Comment by sandhyasun** [comment]
jenkins, ok

**Comment by svarnau** [comment]
Jenkins failed to post result message. It should have been:

Refer to this link for build results (access rights to CI server needed): 
https://jenkins02.trafodion.org/job/Check-PR/35/
Test PASS

**Pull request merged**
