### PR TITLE
[TRAFODION-1737]Fixed jar confiction

### PR DESCRIPTION
**Pull request by kevinxu021**

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, add user

**Comment by arvind-narain** [comment]
Hi Kevin, could you please mention the scenario and the error seen ?

**Comment by kevinxu021** [comment]
Hi Arvind, as you know, DCSServer is a JAVA program and CLASSPATH is required. if you check CLASSPATH, you would notice that there are 2 kinds of jsp-api jar. One has ExpressionFactory.newInstance(), but the other one doesn't.  if JVM loaded the one doest have newInstance(), it will cause the error. Unfortunately, it occurs on my VM. Anyway, it's not reasonable to include more than one version for the same project JAR.

**Comment by arvind-narain** [comment]
Thanks for the explanation. Suggest to include such information in future Jiras/pull request. Will merge in shortly.

**Pull request merged**
