### PR TITLE
Testing with small change

### PR DESCRIPTION
**Pull request by amandamoran**
Removed a package we no longer need to install, mostly for testing purposes.

### CODE REVIEW

**Comment by zellerh** [comment]
+1 from me.

**Comment by svarnau** [comment]
jenkins, add user

**Comment by robertamarton** [comment]
+1 from me

**Comment by amandamoran** [comment]
Jerkins passed so I will commit this code myself as practice. Thanks!

**Comment by svarnau** [comment]
Yes, I'm still debugging Jenkins. It is getting triggered, but unable to post comments. The message it tried to post is:

Refer to this link for build results (access rights to CI server needed): 
 https://jenkins02.trafodion.org/job/Check-PR/38/
Test PASS

**Comment by amandamoran** [comment]
Hooray!

**Pull request merged**
