### PR TITLE
[TRAFODION-2125] ID request times out to idtmsrv process

### PR DESCRIPTION
**Pull request by sbroeder**

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good to me. One question: Why is the do_link function in a header file?

**Comment by svarnau** [comment]
jenkins, retest -- automation bug

**Comment by sbroeder** [comment]
jenkins, retest

**Comment by svarnau** [comment]
jenkins, retest -- second automation bug

**Comment by selvaganesang** [comment]
Where is the output of printf seen in idtmserv process? If it is a server process, is it possible to use log4cxx which is being enabled in TM via #604

**Comment by sbroeder** [comment]
The output goes to stdout_idtmsrv_0.   It's certainly possible to route the output to a different location, and it's probably a good idea, but I think that should be part of a separate commit since that's not the defect being addressed here.


________________________________

**Pull request merged**
