### PR TITLE
Updated the website to use the new Apache incubator logo. Also, updated

### PR DESCRIPTION
**Pull request by gtapper**
versions on the pom.xml file to a new version of the PDF generator. This
version exposes the Messages Guide, which now uses the env.TRAFODION_VER
variable. The docs/messages_guide needs to be built for 1.3.0 and 2.0.0
and checked in accordingly to the website git branch.

This pull request also includes the first checkin of the upcoming
Provisioning Guide, which replaces the never-published Installation Guide.

Finally, removed the asciidoc handling in the main pom.xml file since it
is not used and was wrong anyway.

### CODE REVIEW

**Comment by svarnau** [comment]
Did not review content of provisioning, but all the pom changes and documentation page look good.

**Comment by gtapper** [comment]
Please update the website when possible.

**Comment by DaveBirdsall** [comment]
Done.

**Comment by gtapper** [comment]
Hmmm... something went wrong, the image isn't in place.


On Fri, Feb 12, 2016 at 3:30 PM, DaveBirdsall <notifications@github.com>
wrote:

> Done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/316#issuecomment-183511950>
> .
>



-- 
Thanks,

Gunnar
*If you think you can you can, if you think you can't you're right.*

**Pull request merged**
