### PR TITLE
TRAFODION-2787 jdbc does not implement wrapper related api

### PR DESCRIPTION
**Pull request by gpj1987**
when use jdbc there is not implement Wrapper with unwrap and isWrapperFor method

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, ok to test

**Comment by svarnau** [comment]
Failed the static RAT checks, because the new file does not have license header.

**Comment by selvaganesang** [comment]
Code looks good, but needs update to new file to include license header

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Pull request merged**
