### PR TITLE
[TRAFODION-1540] Replace host name with IP address

### PR DESCRIPTION
**Pull request by kevinxu021**
#133 has been closed. this new pull request is to solve conflict issue

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, add user

**Comment by arvind-narain** [comment]
Thanks for the change Kevin. Looks good to me.

**Comment by kevinxu021** [comment]
Arvind, thanks for review. if no more comments, could you please merge the code since i don't have permission?

**Comment by arvind-narain** [comment]
Sorry about the delay. I did want to test out the patch but didn't get the chance earlier. Could you also look into the following directory jamon/org/trafodion/dcs/tmpl and particularly ServerStatusTmpl.jamon and check if similar changes are needed there ( I looked at the link for Home ) ?

**Comment by sureshsubbiah** [comment]
Arvind, Kevin : Is this PR ready to be merged? I could not determine from conversation here if any further action by author or reviewer is required now. Thank you all.

**Comment by arvind-narain** [comment]
I'm offline currently but the last comment by me was to make changes in the other files so that the links on all pages use the underlying IP address, to be consistent with the current change.

-----Original Message-----

**Comment by kevinxu021** [comment]
Suresh/Arvind, it's fine to merge since it's an enhancement and more files related than this one. So the changes will be made in the another coming pull-request. i'm busy on SPJ which seems to be more urgent.

**Comment by kevinxu021** [comment]
Suresh, Arvind, All changes are made in this pull-request. Feel free to merge it. i have confirmed with installation guys for looking up IP by host name. Since mappings must store in /etc/hosts, the changes are more easy. By the way, it also applies for singleton Trafodion instance.

**Comment by hegdean** [comment]
changes look good to me

**Comment by arvind-narain** [comment]
Thanks Kevin. Looks good now. Suresh - could you please merge this in ?

**Pull request merged**
