### PR TITLE
[TRAFODION-22]: fix JIRA22: avg() overflows over large int data type and remove dqatd…

### PR DESCRIPTION
**Pull request by nonstop-qfchen**
This is to fix JIRA22 and remove the known diff file for regression test qat qatdml04. Anoop has reviewed the change.

### CODE REVIEW

**Comment by svarnau** [comment]
Please fix pull-request title to have [TRAFODION-22] at beginning of title.

**Comment by nonstop-qfchen** [comment]
Is there an easy way to modify the title without re-submit a change?  My
local branch is in a messy state that git does not allow a branch
switching.

Appreciate any help.

On Mon, Jul 13, 2015 at 10:03 AM, Steve Varnau <notifications@github.com>
wrote:

> Please fix pull-request title to have [TRAFODION-22] at beginning of title.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/24#issuecomment-120960429>
> .
>



-- 
Regards, --Qifan

**Comment by nonstop-qfchen** [comment]
Yes, just go to the PR page, you should be able to edit the title there.

On Mon, Jul 13, 2015 at 8:10 AM, Qifan Chen <qifan.chen@esgyn.com> wrote:

> Is there an easy way to modify the title without re-submit a change?  My
> local branch is in a messy state that git does not allow a branch
> switching.
>
> Appreciate any help.
>
> On Mon, Jul 13, 2015 at 10:03 AM, Steve Varnau <notifications@github.com>
> wrote:
>
>> Please fix pull-request title to have [TRAFODION-22] at beginning of
>> title.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/apache/incubator-trafodion/pull/24#issuecomment-120960429>
>> .
>>
>
>
>
> --
> Regards, --Qifan
>
>


-- 
-Steve

**Comment by svarnau** [comment]
Not sure why this shows the github hubot as merging this, as it was merged by Dave.
But I think the result is that it interfered with ASF Bot closing this pull-request.
Qifan, can you close it?

**Comment by nonstop-qfchen** [comment]
done.

On Tue, Jul 14, 2015 at 1:15 PM, Steve Varnau <notifications@github.com>
wrote:

> Not sure why this shows the github hubot as merging this, as it was merged
> by Dave.
> But I think the result is that it interfered with ASF Bot closing this
> pull-request.
> Qifan, can you close it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/24#issuecomment-121328016>
> .
>



-- 
Regards, --Qifan

**Comment by DaveBirdsall** [comment]
This pull request doesn't seem to be closed yet... how do we get it closed?

**Comment by svarnau** [comment]
Since the ASF gitbot did not close it, I think Qifan is the only one with permission to close the pull-request.

**Comment by nonstop-qfchen** [comment]
ok.

**Comment by nonstop-qfchen** [comment]
I closed the request.  thanks.

On Fri, Jul 17, 2015 at 4:48 PM, Steve Varnau <notifications@github.com>
wrote:

> Since the ASF gitbot did not close it, I think Qifan is the only one with
> permission to close the pull-request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/24#issuecomment-122427922>
> .
>



-- 
Regards, --Qifan

**Pull request merged**
