### PR TITLE
[TRAFODION-2753]LOB: filetolob() no longer works in trafci

### PR DESCRIPTION
**Pull request by xwq**

### CODE REVIEW

**Comment by sandhyasun** [comment]
+1

**Comment by sandhyasun** [comment]
Once the check test failure in  Phoenix T4 is addressed , this should be good to go.

**Comment by xwq** [comment]
I checked the log, the failure was caused by timeout of "Check HDP service HDFS start status". I will restarted the test.

**Comment by xwq** [comment]
jenkins, retest.

**Pull request merged**
