### PR TITLE
[TRAFODION-2544] JDBCT4 group id needs to be changed to org.apache.trafodion in JAR 

### PR DESCRIPTION
**Pull request by AlexPeng19**
[TRAFODION-2544] JDBCT4 group id needs to be changed to org.apache.trafodion in JAR

### CODE REVIEW

**Comment by AlexPeng19** [comment]
jenkins, retest

**Comment by selvaganesang** [comment]
Is this a requirement from Apache? Changing the package name would mean the existing application needs to be updated to load the new driver isn't?

**Comment by selvaganesang** [comment]
I think there are 2 other issues with this change.  I think the directory of the java programs needs to be in sync with package name for use in eclipse and other IDEs.  @zellerh can confirm this.  In addition, I didn't see the corresponding change in trafci. I wonder if trafci is broken with this change

**Comment by selvaganesang** [comment]
I understood from @arvind-narain that this change is not changing the package name of T4 driver and it just changes the group id in maven.  I misunderstood the change earlier. If this is what is expected in the PR, then the change looks good.

**Comment by DaveBirdsall** [comment]
@selvaganesang, so is this ready to be merged?

**Comment by DaveBirdsall** [comment]
Pinging again, @selvaganesang, is this ready to be merged?

**Comment by selvaganesang** [comment]
Yes. I think so.

**Comment by DaveBirdsall** [comment]
Great! I'll merge it.

**Pull request merged**
