### PR TITLE
Changes to address memory corruption causing core for buffer LOB input  [TRAFODION-2408]

### PR DESCRIPTION
**Pull request by sandhyasun**
A couple of  usages in the test driver program had to be addressed.

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good. Perhaps you could change the title for this pull request to include a JIRA number?

**Comment by sandhyasun** [comment]
jenkins, extra tests

**Comment by selvaganesang** [comment]
Hello @sandhyasun 

I have a general comment though I am not an expert in this area.  The core happened deep in the Trafodion SQL engine with the stack trace as below

#4  0x00007f281c2da322 in JVM_handle_linux_signal () from /usr/lib/jvm/java-1.7.0-openjdk.x86_64/jre/lib/amd64/server/libjvm.so
#5  <signal handler called>
#6  0x00007f281a553740 in memcpy () from /lib64/libc.so.6
#7  0x00007f281c11244a in ?? () from /usr/lib/jvm/java-1.7.0-openjdk.x86_64/jre/lib/amd64/server/libjvm.so
#8  0x00007f281b8e1df8 in hdfsWrite () from /usr/lib64/libhdfs.so.0.0.0
#9  0x00007f2817d2a6ea in ExLob::writeData (this=0x3167240, offset=<value optimized out>, data=0x1 <Address 0x1 out of bounds>, size=50, operLen=@0x7ffd7c82ee60) at ../exp/ExpLOBaccess.cpp:321
#10 0x00007f2817d2c37e in ExLob::writeLobData (this=0x3167240, source=0x1 <Address 0x1 out of bounds>, sourceLen=<value optimized out>, subOperation=Lob_Buffer, tgtOffset=<value optimized out>, operLen=@0x7ffd7c82ee60, lobMaxChunkMemSize=512) at ../exp/ExpLOBaccess.cpp:924
#11 0x00007f2817d2cf73 in ExLob::append (this=0x3167240, data=0x7ffd7c82f840 "\001", size=<value optimized out>, so=Lob_Buffer, headDescNum=<value optimized out>, operLen=@0x7ffd7c82ee60, lobMaxSize=10000, lobMaxChunkMemSize=512, lobGCLimit=5000, handleIn=0x7f280898397c "", handleInLen=68, handleOut=0x7ffd7c82f410 "H\240\210\b\216", handleOutLen=@0x7ffd7c82f850, lobGlobals=0x2a00260) at ../exp/ExpLOBaccess.cpp:1140
#12 0x00007f2817d3275a in ExLobsOper (lobName=0x7f280898517e "LOBP_04746349383199723529_0001", handleIn=0x7f280898397c "", handleInLen=68, hdfsServer=0x7ffd7c82ec80 "\230w\346\002", hdfsPort=<value optimized out>, handleOut=0x7ffd7c82f410 "H\240\210\b\216", handleOutLen=@0x7ffd7c82f850, descNumIn=4746349383880024291, descNumOut=@0x7ffd7c82ee58, retOperLen=@0x7ffd7c82ee60, requestTagIn=0, requestTagOut=@0x7ffd7c82ee58, requestStatus=@0x7ffd7c82ee6c, cliError=@0x7ffd7c82ee50, lobStorageLocation=0x7f28089855b0 "/lobs", storage=Lob_HDFS_File, source=0x7ffd7c82f840 "\001", sourceLen=50, cursorBytes=0, cursorId=0x0, operation=Lob_Append, subOperation=Lob_Buffer, waited=1, globPtr=@0x7ffd7c82ee48, transId=0, blackBox=0x0, blackBoxLen=0, lobMaxSize=10000, lobMaxChunkMemSize=512, lobGCLimit=5000, bufferSize=0, replication=0, blockS

If the testware change takes care of this core, then Trafodion SQL engine code needs to guard itself from dumping core even when there is a problem with testware.

It is possible that I misunderstood the whole issue here.

**Comment by sandhyasun** [comment]
Yes the testware change didn't  fix it. Looking into it further. The test passes on multiple runs on other workstations.  Will see why.

**Comment by sandhyasun** [comment]
jenkins, extra tests

**Comment by sandhyasun** [comment]
The test that was coring now passes with the latest changes.

**Comment by selvaganesang** [comment]
That explains the issue. Looks good

**Pull request merged**
