### PR TITLE
[TRAFODION-1933] Migrate jdbcT4 and trafci build scripts from Ant to Maven

### PR DESCRIPTION
**Pull request by hegdean**
This PR only contains migration changes for jdbcT4.  TRAFCI migration to 
Maven will be done in a seperate JIRA.

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good to me. The conflicts will need to be resolved though.

**Comment by DaveBirdsall** [comment]
Ah, I see the conflicts were resolved just now.

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Comment by svarnau** [comment]
FYI jenkins picks up new commits, so it is not necessary to prompt it in cases like this.  It polls every 10 minutes or so.

**Comment by hegdean** [comment]
jenkins extra tests

**Pull request merged**
