### PR TITLE
[TRAFODION-1438] Fixing Win ODBC crashes with long cert file name length(over 30 bytes)

### PR DESCRIPTION
**Pull request by ryzuo**
Change the driver to determine the length of buffer for certificate
file name at runtime, and fill the name with secured strcpy version(strcpy_s)

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, add user

**Comment by arvind-narain** [comment]
Thanks for the change. Could you please check on the git settings so that the eols are maintained for windows ?

**Comment by hegdean** [comment]
Thanks for the change.  We will run into similar issue when using Linux driver. Can you  please make similar change for linux driver as well.

**Comment by ryzuo** [comment]
For there's the pwd. file under core/sqf/src/tm/tools/ which Windows does not recognize, it makes it's always in the changed list and not able to remove from cache, thus I can't commit from Windows. So I did this via Linux.
Although these are Windows codes, LF is default configuration of git, and conventionally people uses LF when submitting codes into git even for Windows platform code for compliance purposes, and Visual Studio supports LF anyway. I'm thinking we will format all those to LF in the future.

**Pull request merged**
