### PR TITLE
[TRAFODION-1507] Second phase of incubator.trafodion.apache.org update.

### PR DESCRIPTION
**Pull request by svarnau**
Gunnar is not available for a time, I'm submitting this pull-request from his fork. I'll try to respond to any comments to carry it forward.

jenkins, skip test

### CODE REVIEW

**Comment by robertamarton** [comment]
Some general comments - 
The "Back to Top" links don't seem to work correctly, at least an the few I tried.
The dtm-architecture pdf file contains HP copyrights, is this okay?
LInk to "passwordless ssh" on install page not working
LInk to "Backup/Restore" on install page not working
Link to "Trafodion Scanner" on install page not working
Link to "Trafodion Client Installation Guide" on install page not working.


Documentation look good!

**Comment by robertamarton** [comment]
Some of the secondary links on pages don't seem to be working correctly - for example the FAQ and Download page.

Some of the links in release 0.8.0, 0.9.0, 1.0.0, etc are incorrect or point to invalid locations such as a pointer to the SQL reference manual. and pointer to build instructions

The UDF Api Tutorial points to an invalid location
The architecture page points to an invalid location on the issues tracking page and other pages
ON the contribute page, there is supposed to be a link to mailing lists that is not working.

Several issues on the develop page: 
  Link to jira signup does not work.
  Link to Trafodion development list is broken
  The code repository link does not look correct.
  Debugging tips link is broken
  Link to create pull request is broken
  Link to pull request 18 is broken, may want to just remove link
  Link to automated test setup is broken

**Comment by robertamarton** [comment]
Test page - link to Salesforce is broken
Merge page link is broken
Release page:
  link to mit pgp server broken (2 places)
  link to verify signatures is broken
  may want to replace rmarton and Roberta Marton with another name
Create dev environment page - Port Assignments and manage development environment pages are broken

**Comment by gtapper** [comment]
Addressed the broken links found by Roberta.

**Comment by robertamarton** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
I will commit this.

**Pull request merged**
