### PR TITLE
TRAFODION-1643

### PR DESCRIPTION
**Pull request by mashengchen**
after hbase-0.98.8(include 0.98.8), the instantiation process of ScanInfo(class) is different from before, which need KeepDeletedCells(enum) as parameter instead of boolean.

### CODE REVIEW

**Comment by mashengchen** [comment]
is there anyone can help to check why failed?

**Comment by mashengchen** [comment]
restart

**Comment by mashengchen** [comment]
jenkins, retest

**Comment by sbroeder** [comment]
Looks fine to me.

**Comment by svarnau** [comment]
The console logs and install logs for all the tests at the links above show that install has issues because HBase is failing after having the co-processor installed.

*** ERROR[8448] Unable to access Hbase interface. Call to ExpHbaseInterface::checkAndInsertRow returned error HBASE_ACCESS_ERROR(-706). Cause: 
java.io.IOException: java.lang.ExceptionInInitializerError
org.apache.hadoop.hbase.client.transactional.TransactionalTable.checkAndPut(TransactionalTable.java:573)
org.apache.hadoop.hbase.client.transactional.RMInterface.checkAndPut(RMInterface.java:394)
org.trafodion.sql.HTableClient.putRow(HTableClient.java:1015)
org.trafodion.sql.HBaseClient.insertRow(HBaseClient.java:1486)

**Pull request closed without merging**
