### PR TITLE
[TRAFODION-31] Create podling website for Trafodion

### PR DESCRIPTION
**Pull request by alchen99**
Site will be generated using Maven + Maven Fluido Skin. The content will be in AsciiDoctor format and will be rendered to HTML using the Maven Asciidoctor plugin. The AsciiDoctor format is a superset of the AsciiDoc format.

### CODE REVIEW

**Comment by alchen99** [comment]
jenkins, add user

**Comment by alchen99** [comment]
jenkins, ok to test

**Comment by svarnau** [comment]
Jenkins is having trouble posting again, but the test results are here:
https://jenkins02.trafodion.org/job/Check-PR/45/ (PASS)

**Comment by sureshsubbiah** [comment]
I am not able to see the changed files associated with this pull request at 
https://github.com/apache/incubator-trafodion/pull/26/files
Maybe this is because all changes are in the form of additions?

Is there an approach I can to use to see the "diffs" ?

**Comment by alchen99** [comment]
I'm not sure what happened here.  The commit that has the actual changed files is the one previous to the one that this pull request is showing.  I sometimes see the other commit in this pull request but usually I don't see it and I've no idea why.  Anyways you can see the changes @ https://github.com/alchen99/incubator-trafodion/commit/cb7bab3655c78ec5b77deb184030de461893b5fa.  I've already committed this change.  You can see the commit @ https://github.com/apache/incubator-trafodion/commit/4ad81c7a115724d0378d4320791677f12a3adbb8

**Comment by sureshsubbiah** [comment]
Thank you Alice.

Suresh

**Pull request closed without merging**
