### PR TITLE
[TRAFODION-2129] Trafodion to avoid use of deprecated HBase APIs/Classes

### PR DESCRIPTION
**Pull request by selvaganesang**
Avoided the caching of Hbase table instances on the client side to avoid
compaction queue size build up while constantly loading the data

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
+1. Looks good Selva.

**Comment by selvaganesang** [comment]
This change removes HTable/Table caching on the client side of the Trafodion code.  The code to add coprocessor classes at the time of creating HTable instance is removed because it would be drag to instantiate HTable/Table for every hbase operation.  It is a non-issue with Trafodion tables because the TableDescription should have added coprocessor classes automatically at the time of create.  The vanilla hbase table access via Trafodion engine will be non-transactional unless the Trafodion co-processor classes are added to the HTableDescriptor via hbase shell.

For the existing customers who had created Trafodion tables in the very early release of Trafodion also need to add coprocessor classes via hbase shell.

**Comment by sbroeder** [comment]
Looks good to me

**Comment by prashanth-vasudev** [comment]
looks good.

**Pull request merged**
