### PR TITLE
[TRAFODION-1666]script to update win-odbc version

### PR DESCRIPTION
**Pull request by xwq**
[TRAFODION-1666]Need a script to update the version of windows ODBC

### CODE REVIEW

**Comment by xwq** [comment]
Does anyone can make Jenkins retest it. 
The script is only used when we want update the version number.

**Comment by svarnau** [comment]
jenkins, retest

**Comment by xwq** [comment]
This time only JDBC test fail. It looks time out.  Please recheck it again.

**Comment by svarnau** [comment]
@xwq you can leave the retest comment yourself

**Comment by svarnau** [comment]
jenkins, retest

**Comment by xwq** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Pull request merged**
