### PR TITLE
TRAFODION-2016 support hbase1.1 & cdh5.5

### PR DESCRIPTION
**Pull request by mashengchen**
support hbase 1.1 & cdh 5.5
for developer pls do set HBASE_DISTRO before source sqenv.sh
export HBASE_DISTRO=APACHE1.0 (APACHE HBASE1.0)
export HBASE_DISTRO=APACHE1.1 (APACHE HBASE1.1)
export HBASE_DISTRO=CDH5.4 (cloudera 1.0.0-cdh5.4.4) 
export HBASE_DISTRO=CDH5.5 (cloudera 1.0.0-cdh5.5.1) 
export HBASE_DISTRO=HDP (hortonworks 2.3)

HBASE_DISTRO will be determined by HADOOP_TYPE&HBASE VERSION

### CODE REVIEW

**Comment by mashengchen** [comment]
#568

**Comment by traflm** [comment]
jenkins, retest

**Comment by traflm** [comment]
You may mention clearly in the title of the two JIRAs you fixed in this single PR, next time .

**Comment by mashengchen** [comment]
Jenkins retest

**Comment by mashengchen** [comment]
jenkins, retest

**Pull request merged**
