### PR TITLE
[TRAFODION-206][TRAFODION-2018]Support catalog API PROCEDURES and PROCEDURECOLUMNS

### PR DESCRIPTION
**Pull request by kevinxu021**

### CODE REVIEW

**Comment by traflm** [comment]
looks good to me. 
This is a very important feature to support third-party tool integration.

**Comment by kevinxu021** [comment]
Jenkins, retest

**Comment by traflm** [comment]
Can some committer help to give some positive/negative comments on this PR?
This is rather important since without getProcedures() support, integration with Kettle in some use case is blocking, users were waiting for this feature.

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Comment by DaveBirdsall** [comment]
I merged this in using a "--squash", but the automation didn't pick it up. Hence the separate "This closes #572" merge. The SHA for the squash commit was 2f9af4d.

**Pull request closed without merging**
