### PR TITLE
[TRAFODION-2842] Correct the description of connectionTimeout in *Trafodion JDBC Type 4 Programmer’s Reference Guide*

### PR DESCRIPTION
**Pull request by liuyu000**

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Is there a JDBC developer who can review this change?

**Comment by liuyu000** [comment]
Hi Dave, this change is propsed by @xwq 
@xwq could you please help review? Thanks

**Comment by kevinxu021** [comment]
Good to go!

**Comment by liuyu000** [comment]
Thanks @kevinxu021

**Pull request merged**
