### PR TITLE
Testing if adding Trafodion user id to HBase group will fix tests

### PR DESCRIPTION
**Pull request by amandamoran**

### CODE REVIEW

**Comment by zellerh** [comment]
+1

Good thing to try. Probably somebody pointed it out already, in a secure environment where regular HBase and Trafodion are mixed, the system administrators may not want to give Trafodion this blanket permission. But, it will be good to figure out a solution first and then improve it.

**Comment by selvaganesang** [comment]
+1 Thanks for doing this @amandamoran If Trafodion needs to use snapshot, it might need to have this kind of blanket permission. If this is the solution, Trafodion needs to suppress the snapshot usage if this permission is not set.

**Comment by amandamoran** [comment]
jenkins, extra tests

**Comment by amandamoran** [comment]
jenkins, extra tests

**Comment by sandhyasun** [comment]
The Extra Test failure in hive is due to aanother minor difference in results. So this change looks good.

**Comment by sureshsubbiah** [comment]
+1

**Pull request merged**
