### PR TITLE
A couple of python scripts got incorrect comment markers in their cop…

### PR DESCRIPTION
**Pull request by sandhyasun**
…yrgiht. Fixing those as part of previous copyright header fix

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good to me. Just go ahead and commit it once tests pass.

**Comment by sureshsubbiah** [comment]
Merging. Thanks

**Comment by sureshsubbiah** [comment]
I am getting this error. Will try again tomorrow or get help.
error: RPC failed; result=52, HTTP code = 100

**Comment by sureshsubbiah** [comment]
Done. Did not get the error this morning.

**Pull request merged**
