### PR TITLE
[TRAFODION-2319]add missing file resource.h

### PR DESCRIPTION
**Pull request by xwq**

### CODE REVIEW

**Comment by xwq** [comment]
@hegdean 
Hi, Anu. I fixed the error in build.bat and odb.rc. Please help to verify this Pull Request before merging it.

**Comment by hegdean** [comment]
change looks good to me. Thanks

**Comment by ryzuo** [comment]
I'm okay with this change.

**Comment by traflm** [comment]
+1, let me merge it

**Pull request merged**
