### PR TITLE
A new option "-p available" to install_local_hadoop. 

### PR DESCRIPTION
**Pull request by nonstop-qfchen**
With this option, the port range is chosen randomly from the list returned reported by findPort.py script.

### CODE REVIEW

**Comment by zellerh** [comment]
Looks good to me!

**Comment by zellerh** [comment]
Actually, here is one comment I want to make: We currently use the following ranges:

-p rand uses ports between 12000 and 24000
-p fromDisplay uses ports above 24000. If the display is less than 42, it stays below the boundary of the ephemeral range, which usually starts at 32K.

Since -p fromDisplay is meant to be deterministic, -p available should not use ports above 24000, since that would break the idea that once you have a display running, that guarantees a corresponding port range. Could we make -p available stay in the range between 12000 and 24000?

**Comment by nonstop-qfchen** [comment]
Hi Hans,

Thanks for the comment. I have submitted the rework. Thanks --Qifan

On Thu, Dec 17, 2015 at 5:34 PM, Trafodion Automated Test <
notifications@github.com> wrote:

> Test Passed. https://jenkins.esgyn.com/job/Check-PR-master/218/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/234#issuecomment-165615753>
> .
>



-- 
Regards, --Qifan

**Comment by nonstop-qfchen** [comment]
Good to know that the push event went through.  I pushed another one to
make sure it is the case.

#220 should contain the latest rework change.

thanks --Qifan



On Thu, Dec 17, 2015 at 6:51 PM, Trafodion Automated Test <
notifications@github.com> wrote:

> Previous Test Aborted. New Check Test Started:
> https://jenkins.esgyn.com/job/Check-PR-master/220/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/234#issuecomment-165626834>
> .
>



-- 
Regards, --Qifan

**Comment by zellerh** [comment]
Note that this code is not exercised by the Jenkins test, so no need to wait for it (probably could do a skip test).

**Pull request merged**
