### PR TITLE
[TRAFODION-1998]JDBC Type2 column information improve

### PR DESCRIPTION
**Pull request by xwq**
JDBC type2 use query to get the columns information from SQL.
1. For Nullable, use the origin value from SQL
2. For remark, return empty string since not support

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Comment by DaveBirdsall** [comment]
This is just the T2 analogy of https://github.com/apache/incubator-trafodion/pull/487, right? @selvaganesang, if you like this change I think it can be merged immediately.

**Comment by selvaganesang** [comment]
Yes. We can merge @DaveBirdsall

**Comment by DaveBirdsall** [comment]
Will merge it now

**Pull request merged**
