### PR TITLE
Fix for TRAFODION-1923

### PR DESCRIPTION
**Pull request by prashanth-vasudev**
Basically, we now understand why SQL was not able to close the outstanding scanner , 
1. because of cancel and the plan involved esps, it was the esps that get killed which did not have an option to close the scanner.
2. Because of this stale scanner is found in region when drop table is issued.
3. Chore thread in region is able to clean the stale scanner, however it may kick in at different times. 
4. A drop table issued in the meantime appears as hung since region observer intercepts  the region close ( due to drop table) and finds a stale scanner.
5. Fix is to detect this situation in regionobserver and validate if a transaction state object exists for this scanner. If it exists, then the intercept is valid, otherwise let the region close complete.

I have pushed the code and did a PR request so you can review the changes.  However, committers wait till all the regressions in my dev environment complete ( I will send out a message once its done).

### CODE REVIEW

**Comment by shangshengtung** [comment]
A minor suggestion will be line 273 in ScannersListClear: Return false (i.e. keep waiting) if trx-txn-state non-existent or the txn-state is "ABORTED". Both cases imply an orphan scanner and we can skip it, but current change is fine, too.

**Comment by selvaganesang** [comment]
Change looks good. Returning true means there is no active scanner.  So @shangshengtung did you mean return true when the txn-state is 'ABORTED'.  Is the transactionState kept around only when it is 'ABORTED'?  Will 'COMMITTED' state imply orphaned scanner too?

**Comment by shangshengtung** [comment]
The transaction object should get cleaned. In this case, for some reasons, either the transaction object is cleaned but not the scanner, or the transaction is aborted (not cleaned yet)  and the scanner is not. Current change is good enough since aborted trasnaction object should get cleaned. Under rare case, we might have a stale scanner with an aborted (but not cleaned) transaction object (likely a bug). In this situation, it's ok to move ahead by ignoring the stale scanner and aborted transaction object. Let us just use the current change.

**Comment by prashanth-vasudev** [comment]
------------------------------------------------------------------
-- Showing result for core
------------------------------------------------------------------
05/04/16 14:13:46            (DEBUG build)
2016-05-04 07:21:47  TEST000  ### PASS ###
2016-05-04 00:12:08  TEST001  ### PASS ###
2016-05-04 00:13:04  TEST002  ### PASS with known diffs ###
2016-05-04 00:16:29  TEST005  ### PASS ###
2016-05-04 00:17:08  TEST008  ### PASS ###
2016-05-04 00:17:43  TEST010  ### PASS ###
2016-05-04 00:18:04  TEST018  ### PASS ###
2016-05-04 00:20:04  TEST019  ### PASS ###
2016-05-04 00:20:27  TEST020  ### PASS ###
2016-05-04 00:21:10  TEST027  ### PASS ###
2016-05-04 00:22:53  TEST029  ### PASS ###
2016-05-04 00:24:55  TEST032  ### PASS ###
2016-05-04 00:25:18  TEST037  ### PASS ###
2016-05-04 00:28:05  TEST038  ### PASS ###
2016-05-04 00:28:38  TEST041  ### PASS with known diffs ###
2016-05-04 00:36:33  TEST056  ### PASS ###
2016-05-04 00:37:52  TEST061  ### PASS ###
2016-05-04 00:40:35  TEST116  ### PASS ###
2016-05-04 07:25:30  TEST131  ### PASS ###
2016-05-04 07:26:01  TEST162  ### PASS ###
2016-05-04 00:47:10  TESTRTS  ### PASS ###

------------------------------------------------------------------
-- Showing result for compGeneral
------------------------------------------------------------------
05/04/16 14:13:54            (DEBUG build)
2016-05-04 00:48:08  TEST001  ### PASS ###
2016-05-04 00:53:01  TEST004  ### PASS ###
2016-05-04 00:54:03  TEST005  ### PASS ###
2016-05-04 00:55:31  TEST006  ### PASS ###
2016-05-04 00:57:31  TEST011  ### PASS with known diffs ###
2016-05-04 01:03:07  TEST013  ### PASS ###
2016-05-04 01:08:46  TEST015  ### PASS with known diffs ###
2016-05-04 01:09:21  TEST042  ### PASS ###
2016-05-04 01:12:51  TEST062  ### PASS ###
2016-05-04 01:16:06  TEST071  ### PASS ###
2016-05-04 01:16:14  TESTTOK2  ### PASS ###

------------------------------------------------------------------
-- Showing result for executor
------------------------------------------------------------------
05/04/16 14:13:59            (DEBUG build)
2016-05-04 01:17:17  TEST001  ### PASS ###
2016-05-04 01:20:04  TEST002  ### PASS ###
2016-05-04 01:20:29  TEST012  ### PASS ###
2016-05-04 01:26:42  TEST013  ### PASS ###
2016-05-04 01:27:47  TEST014  ### PASS ###
2016-05-04 01:32:34  TEST015  ### PASS ###
2016-05-04 01:33:45  TEST016  ### PASS ###
2016-05-04 01:35:52  TEST020  ### PASS ###
2016-05-04 01:39:25  TEST022  ### PASS ###
2016-05-04 01:40:08  TEST025  ### PASS ###
2016-05-04 01:40:33  TEST050  ### PASS ###
2016-05-04 01:41:18  TEST063  ### PASS ###
2016-05-04 01:41:35  TEST101  ### PASS ###
2016-05-04 01:48:46  TEST106  ### PASS ###
2016-05-04 01:49:58  TEST107  ### PASS ###
2016-05-04 01:54:40  TEST122  ### PASS ###
2016-05-04 02:07:32  TEST130  ### PASS ###
2016-05-04 02:08:27  TEST131  ### PASS ###
2016-05-04 02:08:59  TEST140  ### PASS ###

------------------------------------------------------------------
-- Showing result for seabase
------------------------------------------------------------------
05/04/16 14:14:11            (DEBUG build)
2016-05-04 02:10:14  TEST002  ### PASS ###
2016-05-04 02:13:13  TEST010  ### PASS ###
2016-05-04 02:15:34  TEST011  ### PASS ###
2016-05-04 02:17:34  TEST012  ### PASS ###
2016-05-04 02:18:20  TEST013  ### PASS ###
2016-05-04 02:18:36  TEST014  ### PASS ###
2016-05-04 02:20:18  TEST016  ### PASS ###
2016-05-04 02:20:33  TEST018  ### PASS ###
2016-05-04 02:39:00  TEST020  ### PASS ###
2016-05-04 02:39:23  TEST022  ### PASS ###
2016-05-04 02:40:30  TEST024  ### PASS ###
2016-05-04 02:47:20  TEST025  ### PASS ###
2016-05-04 02:51:07  TEST026  ### PASS ###
2016-05-04 03:01:02  TEST027  ### PASS ###
2016-05-04 03:01:39  TEST028  ### PASS ###
2016-05-04 03:01:48  TEST030  ### PASS ###
2016-05-04 03:03:16  TEST031  ### PASS ###

------------------------------------------------------------------
-- Showing result for fullstack2
------------------------------------------------------------------
05/04/16 14:14:17            (DEBUG build)
2016-05-04 03:04:21  TEST023  ### PASS ###
2016-05-04 03:04:46  TEST053  ### PASS ###
2016-05-04 03:04:53  TEST062  ### PASS ###

------------------------------------------------------------------
-- Showing result for charsets
------------------------------------------------------------------
05/04/16 14:14:18            (DEBUG build)
2016-05-04 03:05:17  TEST001  ### PASS ###
2016-05-04 03:07:58  TEST002  ### PASS ###
2016-05-04 03:08:12  TEST003  ### PASS ###
2016-05-04 03:08:34  TEST004  ### PASS ###
2016-05-04 03:08:49  TEST010  ### PASS ###
2016-05-04 03:09:12  TEST012  ### PASS ###
2016-05-04 03:10:01  TEST014  ### PASS ###
2016-05-04 03:13:23  TEST310  ### PASS ###
2016-05-04 03:16:50  TEST311  ### PASS ###
2016-05-04 03:20:35  TEST312  ### PASS ###
2016-05-04 03:24:36  TEST313  ### PASS ###
2016-05-04 03:24:57  TEST314  ### PASS ###
2016-05-04 03:26:01  TEST315  ### PASS ###

------------------------------------------------------------------
-- Showing result for qat
------------------------------------------------------------------
05/04/16 14:14:25
2016-05-04 03:26:25  qatddl00  ### PASS ###
2016-05-04 03:27:04  qatddl01  ### PASS ###
2016-05-04 03:27:13  qatddl02  ### PASS ###
2016-05-04 03:27:27  qatddl03  ### PASS ###
2016-05-04 03:27:38  qatddl04  ### PASS ###
2016-05-04 03:27:48  qatddl05  ### PASS ###
2016-05-04 03:29:12  qatddl06  ### PASS ###
2016-05-04 03:29:22  qatddl07  ### PASS ###
2016-05-04 03:29:51  qatddl08  ### PASS ###
2016-05-04 03:30:10  qatddl09  ### PASS ###
2016-05-04 03:30:24  qatddl10  ### PASS ###
2016-05-04 03:30:46  qatdml01  ### PASS ###
2016-05-04 03:30:59  qatdml02  ### PASS ###
2016-05-04 03:31:11  qatdml03  ### PASS ###
2016-05-04 03:31:24  qatdml04  ### PASS ###
2016-05-04 03:31:43  qatdml05  ### PASS ###
2016-05-04 03:32:10  qatdml06  ### PASS ###
2016-05-04 03:32:25  qatdml07  ### PASS ###
2016-05-04 03:32:42  qatdml08  ### PASS ###
2016-05-04 03:32:54  qatdml09  ### PASS ###
2016-05-04 03:33:16  qatdml10  ### PASS ###
2016-05-04 03:33:37  qatdml11  ### PASS ###
2016-05-04 03:34:14  qatdml12  ### PASS ###
2016-05-04 03:34:52  qatdml13  ### PASS ###
2016-05-04 03:35:05  qatdml14  ### PASS ###

------------------------------------------------------------------
-- Showing result for privs1
------------------------------------------------------------------
05/04/16 14:14:59
2016-05-04 03:43:24  TEST132  ### PASS ###
2016-05-04 07:30:32  TEST133  ### PASS ###
2016-05-04 03:49:46  TEST136  ### PASS ###
2016-05-04 03:52:50  TEST137  ### PASS ###
2016-05-04 04:02:52  TEST141  ### PASS ###

------------------------------------------------------------------
-- Showing result for privs2
------------------------------------------------------------------
05/04/16 14:15:17
2016-05-04 04:08:48  TEST129  ### PASS ###
2016-05-04 04:15:40  TEST135  ### PASS ###
2016-05-04 04:24:26  TEST138  ### PASS ###
2016-05-04 04:27:09  TEST139  ### PASS ###
2016-05-04 04:31:04  TEST140  ### PASS ###
2016-05-04 04:39:31  TEST142  ### PASS ###

------------------------------------------------------------------
-- Showing result for udr
------------------------------------------------------------------
05/04/2016 14:15
2016-05-04 04:41:55  TEST001  ### PASS ###
2016-05-04 07:34:23  TEST002  ### FAIL (45 lines) ###
2016-05-04 04:45:21  TEST100  ### PASS ###
2016-05-04 04:49:51  TEST101  ### PASS ###
2016-05-04 04:58:17  TEST102  ### PASS ###
2016-05-04 05:00:04  TEST103  ### PASS ###
2016-05-04 05:02:57  TEST107  ### PASS ###
2016-05-04 05:05:38  TEST108  ### PASS ###
2016-05-04 05:06:05  TEST163  ### PASS ###

------------------------------------------------------------------
-- Showing result for hive
------------------------------------------------------------------
05/04/16 14:15:45            (DEBUG build)
2016-05-04 07:37:24  TEST001  ### PASS ###
2016-05-04 07:37:53  TEST002  ### PASS ###
2016-05-04 07:40:13  TEST003  ### PASS ###
2016-05-04 07:41:36  TEST004  ### PASS ###
2016-05-04 07:43:41  TEST005  ### PASS ###
2016-05-04 07:44:04  TEST006  ### PASS ###
2016-05-04 07:45:35  TEST009  ### PASS ###
2016-05-04 07:49:22  TEST015  ### PASS ###
2016-05-04 07:53:54  TEST017  ### PASS ###
2016-05-04 08:01:07  TEST018  ### PASS ###
2016-05-04 08:01:56  TEST020  ### PASS ###
2016-05-04 08:02:27  TEST021  ### PASS ###

*****************************************************************
*
*  Regression tests complete
*
*****************************************************************


udr/Test002 failure seems unrelated
UDR/DIFF002
> *** ERROR[11252] Error 2 on opening directory /logs

**Pull request merged**
