### PR TITLE
TRAFODION-1743 add connection session

### PR DESCRIPTION
**Pull request by mashengchen**
this jira has been merged in #561, but it is strange the changed code in apache/master disappeared. so i do a PR again.
add seesion to each connection.

### CODE REVIEW

**Comment by traflm** [comment]
looks good, thanks

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Comment by selvaganesang** [comment]
Isn't there a need to call end session at the time of disconnect?

**Comment by traflm** [comment]
Oh yes, I agree with selva, need to call end session in Java_org_trafodion_jdbc_t2_SQLMXConnection_close() I guess. Otherwise, it never take effect.

**Comment by traflm** [comment]
it is good now. thanks.

**Comment by DaveBirdsall** [comment]
Merged this; looks like @selvaganesang 's comment was addressed.

**Pull request merged**
