### PR TITLE
[TRAFODION-2701] The maxlength for LargeInt was fixed to 8

### PR DESCRIPTION
**Pull request by Weixin-Xu**
Snprintf using sizeof(__int64) to set the max length of binding char to bigint with 8 chars.
It is too short for bigint.

### CODE REVIEW

**Comment by xwq** [comment]
Jenkins, retest.

**Comment by Weixin-Xu** [comment]
Jenkins, retest.

**Comment by Weixin-Xu** [comment]
Jenkins, retest.

**Comment by xwq** [comment]
Jenkins, retest.

**Comment by Weixin-Xu** [comment]
Jenkins, retest.

**Comment by DaveBirdsall** [comment]
The JDBC tests seem to be failing consistently. Perhaps that needs to be debugged before we can merge this change?

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
The test failure is due to a nowait statement limit problem in the JDBC tests. This particular change is not the cause of that. I am merging this change in spite of the failure.

**Pull request merged**
