### PR TITLE
[TRAFODION-1866] Build should not require qmake

### PR DESCRIPTION
**Pull request by svarnau**

### CODE REVIEW

**Comment by zellerh** [comment]
Looks good to me, thanks for fixing that!

**Comment by zellerh** [comment]
Actually, at second thought: Could we separate the mk.sh and cp commands into two lines and just ignore the exit code of cp? It would be good to catch checkins that break the GUI build. We had that a while ago and had a hard time getting it back to work when we didn't notice the problem immediately.

**Comment by svarnau** [comment]
@zellerh yes, that thought had occurred to me as well to make it into two lines. But you make a good point why that is necessary.  Will do.

**Comment by DaveBirdsall** [comment]
The rework looks good to me.

**Comment by zellerh** [comment]
Looks good to me, too, thanks for making that change.

**Pull request merged**
