### PR TITLE
TRAFODION-1878 Initial commit for adding a portable (docker) build env

### PR DESCRIPTION
**Pull request by nitin-amp**
Initial commit of docker file.

- The first (base) image downloads all the dependencies, as described on [Create Build Env](https://cwiki.apache.org/confluence/display/TRAFODION/Create+Build+Environment) page 
- The second (user) image downloads and installs all the tools, as described on [Build Source](https://cwiki.apache.org/confluence/display/TRAFODION/Build+Source) page

For testing, please run the two scripts in order:
`cd ./tools/docker`
`./build-base-docker.sh`
`./start-compile-docker.sh`

The second one will take long as it needs to install the tools. Once the second container is up and running, follow the build instructions: **debug** `source ./env.sh` or **release**

### CODE REVIEW

**Comment by arvind-narain** [comment]
jenkins, add user

Can one of the admins verify this patch?

—
Reply to this email directly or view it on GitHub
<https://github.com/apache/incubator-trafodion/pull/365#issuecomment-192764166>
.

**Comment by arvind-narain** [comment]
jenkins, retest -- not sure why DCS master got an exception while connecting to zookeeper.

**Comment by traflm** [comment]
I would like to review this, but I have no knowledge about Docker. So I will ask team if there are someone know Docker good.

**Comment by nitin-amp** [comment]
I'll create a wiki page describing the steps to setup a docker environment and validate the scripts.

**Comment by mkby** [comment]
I had a try on these scripts, but the docker images cannot access internet, so it failed at 'yum install epel-release' step. Is there any setting needed for the docker environment?

**Comment by DaveBirdsall** [comment]
Looks good to me, though I am not a Docker or install expert. I checked the license text. I also checked the list of yum packages against the Trafodion wiki.

**Comment by zellerh** [comment]
Looks good to me too. Unless there are objections, I propose we commit this change and address any issues from testing later, given that this is a brand-new feature.

**Comment by DaveBirdsall** [comment]
+1 @zellerh

**Pull request merged**
