### PR TITLE
[TRAFODION-1423] Index improvements- Indexes in aligned Row format

### PR DESCRIPTION
**Pull request by selvaganesang**

### CODE REVIEW

**Comment by selvaganesang** [comment]
I have made quite a bit of changes as per your suggestions. I have created a new branch in my work  space. And github created a new pull request. Now everything seems to work as expected. Things pending:

1.	SHOWDDL and INVOKE should show the aligned row format attributes for indexes
2.	The attribute syntax to work for create indexes
3.	A test scripts in the developer regressions

However, I would like these changes to be pulled into master.

**Comment by selvaganesang** [comment]
Yes. I will wait till this PR is pulled into master

**Comment by DaveBirdsall** [comment]
Code changes look good to me. Perhaps have Hans take another look? If he likes it I'd be happy to commit it.

**Comment by zellerh** [comment]
Yes, looks good to me.

**Pull request merged**
