### PR TITLE
[TRAFODION-1561]List all configurations

### PR DESCRIPTION
**Pull request by kevinxu021**
The way to know what kinds of configurations it has on DCS. More people ask for it. Enjoy.

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, add user

**Comment by DaveBirdsall** [comment]
This is out of my area of expertise, but it looks good to me. Will commit it later today if there are no other comments.

**Comment by hegdean** [comment]
This change is of no harm but helpful during troubleshooting as it displays not only DCS specific configuration but much more than that.  It would have been nice if this was displayed as a link on the main page  which would then show list the entire configuration on a new page rather than on the main page

**Comment by kevinxu021** [comment]
Hegdean, Thanks for your comments. Ref to Apache Storm-UI Topology page. All-in-one instead of switching pages may be helpful here since you may get wanted info by CTRL+F on browser. It may support fold/unfold and something more will be added. But all the other things will be done in another pull-request. By the way, all configurations are from dcs-default.xml and dcs-site.xml. Don't worry, its style and backend might have significant changes in the next milestone.

**Pull request merged**
