### PR TITLE
[TRAFODION-1774]use hashCode instead of random

### PR DESCRIPTION
**Pull request by xwq**
[TRAFODION-1774][MT-DCS]use hashCode() instead of random to make the
stmtHandle is unique

### CODE REVIEW

**Comment by xwq** [comment]
Now, MT-DCS use random.nextInt(1000) to generator a number for statement which used as stmtHandle. However it can't make sure the value it unique for echo statement. hashCode() could be used instead of random.

**Comment by xwq** [comment]
I have test it.In the test When using random.nextInt() it will generator a reduplicate stmtHandle after I creating 20 statements.

**Comment by DaveBirdsall** [comment]
The change looks fine. I'm wondering, though, if hashcode() could return duplicate values? (Perhaps it does so much less frequently.)

**Comment by xwq** [comment]
Jvm can make sure it is unique.

**Comment by xwq** [comment]
JVM can guarantee it's unique. However I think it may return duplicate if there are more than 2^32 objects since it's a INT value. But I don't think we need consider this situation。

**Comment by DaveBirdsall** [comment]
While I agree that a duplicate is less likely with this change, I'm wondering what the impact is when there is a duplicate. Is this still a serious problem from a user perspective? If the objective is simply to get a unique statement identifier, would it make sense to detect that a duplicate occurred and then add a retry loop that would just increment the value until a unique statement identifier is achieved?

**Comment by xwq** [comment]
In many cases, TrafConnection need use the stmtHandle to identify a statement, so we need it is unique. 
TrafStatement itself can't know the stmtHandle of other statements, so we need detect the duplicate in TrafConnection and then set it to TrafStatement. 
I use hashCode() since it make the changes simple, and in Java, hashCode() is a native method , we don't need to worry about the performance.

**Pull request merged**
