### PR TITLE
[TRAFODION-1918] Remove disabling auto flush concept in Trafodion

### PR DESCRIPTION
**Pull request by selvaganesang**
The auto flush is on by default in insertRows method. But insertRows was
incorrectly called with the wrong parameter. In fixing this issue, it was
observed that auto flush is deprecated in HBase 1.x. It is also incorrect
to disable auto flush in Trafodion. Hence removed the code related to
auto flush, flush table and flush all tables in Trafodion.

All these are dormant code in Trafodion.

Also disabled executor/TEST106 for now because it seems to cause a hang
at the time of drop table.

### CODE REVIEW

**Comment by selvaganesang** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Comment by sureshsubbiah** [comment]
Looks good. I suppose TEST106 is being disabled for some other reason? Merging...

**Comment by selvaganesang** [comment]
TEST106 was disabled because of hang issue in drop statement. Prashanth will create a JIRA and work on it.

**Pull request merged**
