### PR TITLE
DO NOT MERGE **TESTING TEST18 failure**

### PR DESCRIPTION
**Pull request by amandamoran**
TESTING ONLY

### CODE REVIEW

**Comment by sandhyasun** [comment]
Test seems to have failed since the command in installer is deprecated. 
MAybe the command issued itself needs an update ?
Here is the error from installer : 
2016-06-09 20:19:05 ***INFO: Setting HDFS ACLs for snapshot scan support
2016-06-09 20:19:11 ***ERROR: (/usr/bin/hdfs dfs -setfacl -R -m user:trafodion:rwx /hbase/archive) command failed
2016-06-09 20:19:11 ***ERROR: traf_cloudera_mods exited with error.
2016-06-09 20:19:11 ***ERROR: Please check log files.
2016-06-09 20:19:11 ***ERROR: Exiting....
2016-06-09 20:19:12 + ret=255

**Comment by amandamoran** [comment]
"Test seems to have failed since the command in installer is deprecated." 
I think @sandhyasun  you are thinking of "hadoop fs" which is deprecated... but as you can see it is using "hdfs dfs" which is not. 

This is related to changing the umask to 0002. Looks like these commands need to be changed to correspond with that. A jira needs to be created to deal with this issue and assigned, this problem is not solved currently.

**Comment by selvaganesang** [comment]
The command seems to have worked in hdp and failed in cdh. Is it possible that /hbase/archive directory is not present in cdh. It might be good to display echo $? as part of the error log. It might give us some clue why the command failed. If the command fails due to non-existence of the directoryh  it should be ok to ignore this error

**Comment by amandamoran** [comment]
echo "***INFO: Setting HDFS ACLs for snapshot scan support"
ssh -q -n $HDFS_NODE 'sudo su hdfs --command "' "$HADOOP_BIN_PATH"'/hdfs dfs -mkdir -p /hbase/archive"'
if [ $? != 0 ]; then
   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive) command failed"
   exit -1
fi
ssh -q -n $HDFS_NODE 'sudo su hdfs --command "' "$HADOOP_BIN_PATH"'/hdfs dfs -chown hbase:hbase /hbase/archive"'
if [ $? != 0 ]; then
   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive) command failed"
   exit -1
fi
ssh -q -n $HDFS_NODE 'sudo su hdfs --command "' "$HADOOP_BIN_PATH"'/hdfs dfs -setfacl -R -m user:'"$TRAF_USER"':rwx /hbase/archive"'
if [ $? != 0 ]; then
   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive) command failed"
   exit -1
fi
ssh -q -n $HDFS_NODE 'sudo su hdfs --command "' "$HADOOP_BIN_PATH"'/hdfs dfs -setfacl -R -m default:user:'"$TRAF_USER"':rwx /hbase/archive"'
if [ $? != 0 ]; then
   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive) command failed"
   exit -1
fi
ssh -q -n $HDFS_NODE 'sudo su hdfs --command "' "$HADOOP_BIN_PATH"'/hdfs dfs -setfacl -R -m mask::rwx /hbase/archive"'
if [ $? != 0 ]; then
   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m mask::rwx /hbase/archive) command failed"
   exit -1
fi

**Comment by selvaganesang** [comment]
In that case, is ACL enabled in cdh? If so, we can try without -R option.

**Comment by amandamoran** [comment]
"items": [ {
             "name":"dfs_namenode_acls_enabled",
             "value":"true"
             }, {
             "name":"fs_permissions_umask-mode",
             "value":"0002"          
             } ]
}' 

This command hasn't changed.... it worked until we changed the umask. They are linked.

**Comment by amandamoran** [comment]
jenkins retest

**Comment by sandhyasun** [comment]
jenkins, extra tests

**Comment by sandhyasun** [comment]
jenkins, extra tests

**Comment by amandamoran** [comment]
jenkins, extra tests

**Pull request closed without merging**
