### PR TITLE
Trafodion 1699

### PR DESCRIPTION
**Pull request by gtapper**
Added Google Analytics Tracking to all .html pages. Code: **UA-72491210-1**.

For the website pages, this is accomplished by adding
**\<googleAnalyticsAccountID\>** tag to the `site.xml` file.

For asciidoc files, an extension from asciidoc-extension-labs provides the
needed function:
https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/google-analytics-postprocessor.rb

**LICENSE NOTICE**

Like asciidoc itself, this extension uses the MIT license.

In addition, it has a dependency on jruby.

**RELEASE INSTRUCTIONS**

Please build the website and the asciidoc files as documented at:
http://trafodion.apache.org/document.html#publish

There no real need to replace the .pdf files but it's simpler to replace
all the latest and 1.3.0 documentation.

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, add user

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Comment by gtapper** [comment]
I don't think it can actually build the documents since I forgot to add the
new docs/shared folder. Checking.

On Tue, Jan 19, 2016 at 4:39 PM, DaveBirdsall <notifications@github.com>
wrote:

> Looks good to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/271#issuecomment-173024163>
> .
>



-- 
Thanks,

Gunnar
*If you think you can you can, if you think you can't you're right.*

**Comment by gtapper** [comment]
Fixed the issue with the missing folder and also dealt with license info.

**Comment by gtapper** [comment]
jenkins, add user

On Tue, Jan 19, 2016 at 10:55 PM, Trafodion Automated Test <
notifications@github.com> wrote:

> Test Passed. https://jenkins.esgyn.com/job/Check-PR-master/337/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/271#issuecomment-173096307>
> .
>



-- 
Thanks,

Gunnar
*If you think you can you can, if you think you can't you're right.*

**Comment by DaveBirdsall** [comment]
I think this is ready to commit.

**Comment by gtapper** [comment]
Source only check-in for the new Trafodion Messages Manual. The pull request still seems active so I did not create a new one. Once integrated, other developers can update the messages as needed.

**Pull request merged**
