### PR TITLE
Fix #1369853

### PR DESCRIPTION
**Pull request by ZhangXiuzhu**
T2 and T4 drivers return different errors if fetch/get data is issued
when cursor is after last row.

Change-Id: Ia91119b57c147e43ad5ea06fe1fd2c28ceca7c52

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, ok to test

**Comment by svarnau** [comment]
jenkins, retest please -- very strange build error

**Comment by svarnau** [comment]
This fails test because of the merge conflict. The test tries to use the merged version of the pull request. Since it doesn't merge, nothing to test.  I'll try to make that more obvious for the future.

**Comment by xwq** [comment]
I don't make sure who will review the changes about JDBC now . But I think -D_DEBUG option is very useful for developer. If the test passed, can anyone merged it. The changes only worked with -D_DEBUG option.

**Comment by svarnau** [comment]
My previous comment was incorrect. There was no "merge" version to test, but it did have your branch version to test. The real problem was since you have not merged up to when the source tree was restructured. The test automation is expecting this code to be under the core directory.

**Comment by xwq** [comment]
This pull request contain 2 commits. I think the commit 6f6017f76ce569ada36eecbc45de6f3e3633d6fb shouldn't be merged.

**Pull request merged**
