### PR TITLE
[[TRAFODION-2036]] Need to add traf user to hbase group on all nodes

### PR DESCRIPTION
**Pull request by amandamoran**

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Comment by sureshsubbiah** [comment]
Sorry for merging the previous PR prematurely. This looks good to me. Will wait for Sandhya and Roberta to comment before merging.

**Comment by sandhyasun** [comment]
Looks good.

**Comment by amandamoran** [comment]
@sureshsubbiah Thanks for the help! I only said "test" and not "do not merge" so I see now that wasn't clear :( Appreciate you being on top of everything though!! :+1:

**Pull request merged**
