### PR TITLE
[[ TRAFODION-1434 ]] Allows for oneclick installs and HDP 2.3 install support

### PR DESCRIPTION
**Pull request by amandamoran**

### CODE REVIEW

**Comment by amandamoran** [comment]
I see there is an issue with traf_sqconfig (for some reason I had an old version!). Will fix.

**Comment by sureshsubbiah** [comment]
Since PR tests are failing we should wait till these are resolved to merge this change.

**Comment by amandamoran** [comment]
jenkins, retest

**Comment by amandamoran** [comment]
jenkins, retest

**Comment by amandamoran** [comment]
Changes tested and ready for merge :)

**Comment by svarnau** [comment]
Disregard latest test result.  Inadvertent test was cancelled.

**Pull request merged**
