### PR TITLE
[TRAFODION-1527] Dcs Webui shows the dcs version as unknown

### PR DESCRIPTION
**Pull request by hegdean**
Added a new target to Makefile(toplevel and core) to install traf components
 (Ex: make trafinstall)
Updated the format of DCS log files
Fixed minor issues

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks OK to me. Will this cause changes to the steps developers use in workstation environments?

**Comment by hegdean** [comment]
This won't cause any change to developers build step. I have just introduced another target to Makefile (of both core and toplevel) to install traf components. Developers can either do 'make trafinstall' after make step is done OR use the previous step of executing 'install_traf_components' it is one of the other

**Comment by hegdean** [comment]
jenkins, retest

**Comment by sureshsubbiah** [comment]
Looks good. Thank you. Merging.

**Pull request merged**
