### PR TITLE
Jira 1531

### PR DESCRIPTION
**Pull request by bucaojit**

### CODE REVIEW

**Comment by narendragoyal** [comment]
Looks good! Nice refactoring that will help with future code maintenance!

**Comment by sbroeder** [comment]
Looks correct, but do we need similar checks in put/delete<list of>?

**Comment by bucaojit** [comment]
Hi Sean.  Yes, I added the checkRow for both the list of puts/deletes and single put/delete.  The put(List) actually calls the put(single) in the code so the checkRow on line 3935 covers both cases.  As for delete, single delete is line 3641 and delete(List) is line 3661.

**Comment by sbroeder** [comment]
Got it.  This looks fine.  Thanks Oliver.

**Comment by sureshsubbiah** [comment]
Merging. Thanks for change and the review all.

**Pull request merged**
