### PR TITLE
Fix for issue where the writeOrdering list was not processed in a con…

### PR DESCRIPTION
**Pull request by sbroeder**
…sistent order and could result in rows being truncated

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
I see other places in this file where we call writeOrdering.listIterator (for example, line 546). Why don't we add the writeOrdering.size() parameter there?

**Comment by sbroeder** [comment]
We only use the writeOrder.size() when we are adding a new put/delete to the writeOrder list to ensure that the items are added at the end of the list.  Otherwise, when iterating through the list we see the newest items first rather than the oldest items first.


________________________________

**Comment by sbroeder** [comment]
jenkins, retest

**Comment by shangshengtung** [comment]
The changes are good to me.

**Comment by DaveBirdsall** [comment]
Looks good.

**Pull request merged**
