### PR TITLE
[TRAFODION-1442] Fixing Linux ODBC driver for long cert file name length supporting ability(over 30bytes)

### PR DESCRIPTION
**Pull request by ryzuo**
This fixes the same problem of Linux ODBC driver as in Windows Driver problem described in JIRA 1438.

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
jenkins, add user

**Comment by arvind-narain** [comment]
This change seems to include the change for windows driver also. Dave could you please advice if this is ok ? Commit tab says 6 commits.

**Comment by sureshsubbiah** [comment]
Since that change was merged in today morning I am assuming that it will be safe to merge this. If there are no objections in the next few hours I will merge it in by end of day. Thank you.

**Comment by arvind-narain** [comment]
Thanks Suresh.

**Comment by sureshsubbiah** [comment]
The merge picked up only the linux file though this pull request says two files. Here is a cut/paste from the screen I used for the merge. Thanks for the heads up Arvind.

Sorry cut/paste from VNC is not working. The file picked up is core/conn/security_dll/native/source/secpwd.cpp . The other win-odbc file was not picked up.

**Comment by ryzuo** [comment]
Hmm... I created the branch from master, should not merge the Windows changes, have no idea why is this happening...

**Pull request merged**
