### PR TITLE
[TRAFODION-1676] rework to solve TEST022 failure

### PR DESCRIPTION
**Pull request by traflm**
Modify the EXPECT file for executor/TEST022 which broke the regression test.
Sorry that I didn't do a full regression before check-in, should do 'Jenkins, extra tests' to trigger more tests.

### CODE REVIEW

**Comment by zellerh** [comment]
Looks good, committing the changes now, since they don't require much discussion and since the check test failures are unrelated (not in executor tests).

**Comment by traflm** [comment]
Jenkins, extra tests

**Comment by traflm** [comment]
thanks Hans for merge this, yes, it is to fix the regression test failure, so should be merged asap. I trigger an extra tests to verify again. I did regression on my dev workstation and seems good.

**Comment by sandhyasun** [comment]
Thanks for making the fix so quickly.

**Pull request merged**
