### PR TITLE
[TRAFODION-1714] Sample table population plan now printed before exec…

### PR DESCRIPTION
**Pull request by DaveBirdsall**
…ution

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
Re: "just wonder..." Which line did you have in mind?

**Comment by selvaganesang** [comment]
It looks like this function might be having a resource leak already. The stmt, srcDesc are not getting deallocated from SQL. If so, it would be good to fix it.

**Comment by zellerh** [comment]
Looks good to me, too.

**Comment by DaveBirdsall** [comment]
Hi Selva. I think the original author covered the resource leak problem. In line 207 of the new file, an HSRef object is created referencing the statement descriptor and the source text input descriptor. The HSRef destructor deallocates those objects. This is a nice technique actually because the HSRef object is created as a stack variable so its destructor will always be called (well, except for a longjmp).

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
I will commit this change as soon as tests pass.

**Comment by selvaganesang** [comment]
Thanks Dave for your explanation. Yes. It is a clever technique.

**Pull request merged**
