### PR TITLE
[TRAFODION-30]dcs start fails on development workspaces when

### PR DESCRIPTION
**Pull request by hegdean**
using install_local_hadoop

Fixed the local hadoop script so servers file in $DCS_INSTALL_DIR
/conf folder is generated correctly. Also took care of the default
github location for DCS/REST and Phoenix tests

### CODE REVIEW

**Comment by zellerh** [comment]
Looks good to me, thanks for the fix.

**Comment by hegdean** [comment]
jenkins, ok to test

**Comment by DaveBirdsall** [comment]
The code looks good to me also. Thanks!

**Comment by arvind-narain** [comment]
Looks good - thanks.

**Comment by svarnau** [comment]
jenkins, add user

**Comment by svarnau** [comment]
Test results: https://jenkins02.trafodion.org/job/Check-PR/50/ (PASS)

**Pull request merged**
