### PR TITLE
[TRAFODION-1747] Avoid generating SQL errors in successful statements.

### PR DESCRIPTION
**Pull request by zellerh**
Using the "reportError" parameter in the underlying method to avoid
generating an error when we just want to test whether a certain
object name is registered in the OBJECTS table.

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good to me. Code is simpler than before. And I imagine will be less tedious to debug.

**Comment by selvaganesang** [comment]
Looks good to me. But, do you think we should do the same with other callers of getObjectUID?

**Comment by sureshsubbiah** [comment]
Looks good to me. Thanks.

**Comment by zellerh** [comment]
Thanks to the reviewers. Selva, what I changed is a static function and I also renamed it, so all the callers of this function have been changed. The other calls to getObjectUID are calls to a method.

**Pull request merged**
