### PR TITLE
[TRAFODION-1417] Reduce locations to change release version number

### PR DESCRIPTION
**Pull request by svarnau**
To change the trafodion release version major/minor number, there were about a dozen locations in four different files that needed to be modified.

This set of changes eliminates all those places except for the single place in core/sqf/sqenvcom.sh.

It does add maven warnings in DCS and REST build logs, same as in other components that already use maven with environment variable version number.

jdbc_test.py script now takes additional options to pass in correct version numbers. If you use swjdbc script, then it is taken care of. Other environments that call jdbc_test.py directly (e.g., jenkins test automation) should also be changed. But the default values match the current release, so the change is not urgent.

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Wonderful change! Reduces the opportunity for human error when we change versions.

**Comment by hegdean** [comment]
Finally we  fixed it. Thanks.  Changes  look good to me.

**Comment by arvind-narain** [comment]
Thanks Steve for this change - looks good

**Comment by zellerh** [comment]
See also TRAFODION-1522. To get rid of the warnings eventually, we can try to make a Maven project hierarchy and then change the version in the top-level pom.xml file. That would add one more place to update the version, but I hope that would be acceptable. Sorry, didn't get to work on this project hierarchy yet.

**Pull request merged**
