### PR TITLE
TRAFODION-1501 Packaging trafodion source is missing in build script

### PR DESCRIPTION
**Pull request by hegdean**

### CODE REVIEW

**Comment by hegdean** [comment]
jenkins, retest

**Comment by hegdean** [comment]
jenkins, retest

**Comment by arvind-narain** [comment]
looks good. Do we want to create a separate JIRA for the test failure (PR 179) ? Not related to this change.

**Comment by arvind-narain** [comment]
Dave could you please merge this change ? Thanks

**Pull request merged**
