### PR TITLE
Fix for JIRA 1712. Use of option -p in hadoop fs -mkdir

### PR DESCRIPTION
**Pull request by sandhyasun**

### CODE REVIEW

**Comment by svarnau** [comment]
Looks good to me.  Helps a bunch on test automation. Thanks.

**Comment by sandhyasun** [comment]
jenkins retest

**Comment by sandhyasun** [comment]
jenkins, retest

**Comment by svarnau** [comment]
jenkins, retest

**Comment by sandhyasun** [comment]
jenkins, retest

**Comment by DaveBirdsall** [comment]
jenkins, retest

**Pull request merged**
