### PR TITLE
JIRA TRAFODION-2834 Streamline supported xn access modes

### PR DESCRIPTION
**Pull request by anoopsharma00**
More details in jira.

traf DTM only supports 'read committed access' for selects
and 'set transaction ' stmts.
With this checkin, only those 2 options will be allowed.
All other access options will return an error.
Read uncommitted access will be treated as read committed.

### CODE REVIEW

**Comment by anoopsharma00** [comment]
jenkins retest

**Comment by anoopsharma00** [comment]
jenkins retest

**Comment by selvaganesang** [comment]
jenkins, retest

**Comment by selvaganesang** [comment]
Looks good. I wonder if you can references to DP2LockFlags or rename them.

**Comment by anoopsharma00** [comment]
Thanks. Will remove/rename it as part of next round of code cleanup.

**Pull request merged**
