### PR TITLE
Fix for TRAFODION-1623

### PR DESCRIPTION
**Pull request by robertamarton**
Removed mvn in path check from sqenvcom.sh

### CODE REVIEW

**Comment by svarnau** [comment]
if you want to retain the error check, then it should go into core/bldenvchk.sh script that is run only during build time, not runtime.

**Comment by zellerh** [comment]
Looks good to me. Putting it into bldenvchk.sh is good, but if the build fails, the error message should be fairly clear and easy to diagnose without a special check.

**Comment by robertamarton** [comment]
The check is already in bldenvchk, I just also erroneously added it to
sqenvcom.sh.



     Roberta



*From:* Steve Varnau [mailto:notifications@github.com]
*Sent:* Thursday, November 12, 2015 5:23 PM
*To:* apache/incubator-trafodion <incubator-trafodion@noreply.github.com>
*Cc:* Roberta Marton <roberta.marton@esgyn.com>
*Subject:* Re: [incubator-trafodion] Fix for TRAFODION-1623 (#171)



if you want to retain the error check, then it should go into
core/bldenvchk.sh script that is run only during build time, not runtime.

—
Reply to this email directly or view it on GitHub
<https://github.com/apache/incubator-trafodion/pull/171#issuecomment-156288465>
.

**Comment by svarnau** [comment]
You're right, it is already in the bldenvchk.sh!  Looks good to me.

**Comment by svarnau** [comment]
jenkins, retest -- infrastructure change was pre-mature for 1.3 release; jar file fix not back-ported to this branch.

**Pull request merged**
