### PR TITLE
[TRAFODION-1860,1875]

### PR DESCRIPTION
**Pull request by mkby**
remove dependency of ctime.pl

### CODE REVIEW

**Comment by traflm** [comment]
Looks very good for me. 
This not only help for CentOS 7, but also other Linux dist in the future. We should reduce unnecessary dependencies as much as possible.

**Comment by svarnau** [comment]
jenkins, add user

**Comment by svarnau** [comment]
jenkins, retest -- hbase re-start failed during trafodion install on only one machine.

**Comment by DaveBirdsall** [comment]
Looks good to me. If there are no further comments, I will commit this tomorrow morning (USA time).

**Pull request merged**
