### PR TITLE
Fix for JIRA TRAFODION-1748

### PR DESCRIPTION
**Pull request by sbroeder**
UnknownTransactionException in prepare causes error 97

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks OK to me. I take it the fix to the bug is the change in TransactionRegionLocation.java, while the other changes are simply to give more logging detail?

**Comment by sbroeder** [comment]
Thanks Dave.  You're correct.  The real fix is to realize that if a new region's start and end keys are contained withing the existing region's start and end keys it is the same region.

**Comment by svarnau** [comment]
jenkins, add user

**Comment by narendragoyal** [comment]
Looks good to me.

**Comment by sbroeder** [comment]
Thanks Narendra.


________________________________

**Pull request merged**
