### PR TITLE
[TRAFODION-2364]convert trafci project into maven project

### PR DESCRIPTION
**Pull request by AlexPeng19**
[TRAFODION-2364]convert trafci project into maven project

### CODE REVIEW

**Comment by AlexPeng19** [comment]
jenkins,retest

**Comment by AlexPeng19** [comment]
jenkins,retest

**Comment by AlexPeng19** [comment]
jenkins,retest

**Comment by AlexPeng19** [comment]
jenkins,retest

**Comment by kevinxu021** [comment]
=== Tue Nov 22 10:54:10 UTC 2016: /usr/local/bin/install-traf.sh
=== Installing Trafodion Command Interface
========================================================
unzip:  cannot find or open trafci.zip, trafci.zip.zip or trafci.zip.ZIP.
Error: Unable to access jarfile trafciInstaller.jar
ERROR: Could not install Trafodion Command Interface
+ exit 1

**Comment by kevinxu021** [comment]
Error message:
=== Tue Nov 22 10:54:10 UTC 2016: /usr/local/bin/install-traf.sh
=== Installing Trafodion Command Interface
========================================================
unzip:  cannot find or open trafci.zip, trafci.zip.zip or trafci.zip.ZIP.
Error: Unable to access jarfile trafciInstaller.jar
ERROR: Could not install Trafodion Command Interface
+ exit 1

**Comment by svarnau** [comment]
Thanks for looking at that, @kevinxu021 
The test jobs that use trafci are trying to install it, but this PR changes the method to install it.

First, the new trafci is not getting included in the clients tar file. See the build artifacts at https://jenkins.esgyn.com/job/build-rh6-master-release/528/. So that needs to get fixed. See core/conn/Makefile.
Second, if the trafci installation method needs to cahnge, please let me know so I can update test automation. Posting the info on dev list would be great.

**Comment by venkat1m** [comment]
env.TRAFODION_VER should work in the maven pom.xml.  Even though there are some warnings displayed, this convention works. DCS and REST components work this way. Without the "env." the ${TRAFODION_VER} will be evaluated as a local property inside the pom. Not sure how the build worked.

**Comment by AlexPeng19** [comment]
thanks for your comments, @svarnau , i have convert the trafci project into maven project. now the install way is only need to do the make instead of ant. i have changed the core/conn/Makefile, Not sure whereto change the trafci method you mentioned. or only you have privilege to do that. please give suggestion.

**Comment by AlexPeng19** [comment]
hmm, thanks for you comments @venkat1m , Not sure why it did not work, i refered the dbmgr to set the variable, but it failed, then i noticed the   JDBCT4 used TRAFODION_VER, so i want to give a shot.

**Comment by svarnau** [comment]
So you are saying that the result of the build should be same zip file as before?  The end user would not necessarily do a "make". One does a make package to build tarfiles, including the clients tarfile, which should include the trafci.zip file.  If you get that to work, then there should be no changes needed to the test automation.

**Comment by AlexPeng19** [comment]
jenkins,retest

**Comment by AlexPeng19** [comment]
jenkins,retest

**Comment by hegdean** [comment]
Can you please add some basic junit testcase for trafci

**Comment by AlexPeng19** [comment]
@hegdean as for this kind of project transfer, not sure how to add junit. you know it's not related to feature, even code. could you give some guide.

**Comment by AlexPeng19** [comment]
jenkins,retest

**Comment by AlexPeng19** [comment]
jenkins,retest

**Comment by AlexPeng19** [comment]
@hegdean i added the junit dependency in maven and create simple test case UserInterfaceTest.java for UserInterface.java. please check.

**Comment by traflm** [comment]
jenkins, extra tests

**Comment by traflm** [comment]
extra test failure is a known issue. So it is good.
I vote to merge this PR. JUnit should not be a must for this PR.  We need unit test cases for TrafCI, and we can create a new JIRA for that purpose. This PR is only to replace ANT with MAVEN. And allow some other important enhancement to trafCI can be made.

**Pull request merged**
