### PR TITLE
TRAFODION-1461 Install scripts have hard coded values for Hadoop admin and password

### PR DESCRIPTION
**Pull request by radumarias**
Using $username:$password instead or hardcoded admin:admin.

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
jenkins, add user

**Comment by sureshsubbiah** [comment]
Change looks great. Thank you very much for this contribution.

**Comment by DaveBirdsall** [comment]
Thanks for this change. Looks good to me also. Amanda, do you want to commit this if you agree?

**Comment by amandamoran** [comment]
Thanks Radu! Looks great. When testing is complete I will merge it in!

**Pull request merged**
