### PR TITLE
[TRAFODION 1511] Phoenix tests when using T2 driver fails with Index out of range error

### PR DESCRIPTION
**Pull request by hegdean**
Updated license file for Linux Driver

### CODE REVIEW

**Comment by svarnau** [comment]
Looks good to me.

**Comment by arvind-narain** [comment]
Looks good to me too.

Steve - can phoenix T2 tests be run separately for change (rather than wait till daily build ) ?

Suresh/Dave - I'll try and merge this once the tests finish.

**Comment by svarnau** [comment]
Yes, jenkins is set up to request particular tests against particular Pull Request. I have started phoenix-T2 against this PR: https://jenkins.esgyn.com/job/phoenix_test_T2-cm5.3/1/console

**Comment by arvind-narain** [comment]
Starting the merge. Looks like Steve's request to run T2 tests ran with a different build, hence seeing similar failures as reported earlier. Will check with daily builds.

**Pull request merged**
