### PR TITLE
TRAFODION-1480 Alternative to lscpu to get cores and cpus using info from /proc/cpuinfo

### PR DESCRIPTION
**Pull request by radumarias**
- Try to get cores and processors from /proc/cpuinfo when we cannot get from lscpu.

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
jenkins, add user

**Comment by sureshsubbiah** [comment]
Thank you for this change. It looks great.

**Comment by DaveBirdsall** [comment]
Thanks also for this change. It looks good to me also. Amanda, do you want to take a look and do the committing honors if you agree?

**Comment by amandamoran** [comment]
Looks great! Thanks so much for finding this issue and fixing it!

**Pull request merged**
