### PR TITLE
TRAFODION-1648 Region Split/Move work

### PR DESCRIPTION
**Pull request by trinakrug**
Rework of Region Split/Move code.  Enhanced error handling and ability to split/move with active transactions.

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Looks good to me. But it is out of my area of expertise. Will commit this if someone from within this area of expertise gives it the OK.

**Comment by sbroeder** [comment]
Looks good, although the formatting seems weird in places.  Looks like there are a lot of white space errors (tabs).  Logic is good.

**Comment by trinakrug** [comment]
Most the formatting changes you see are actual differences in spacing.  It has to do with adding an if statement that surrounds an existing block of code, so all the code in those blocks were indented by 4 spaces.

**Comment by sbroeder** [comment]
Thanks for clarifying Trina!

**Pull request merged**
