### PR TITLE
[TRAFODION-2697] Set bulkload permissions for hbase upload

### PR DESCRIPTION
**Pull request by svarnau**
Both ambari and python installers

### CODE REVIEW

**Comment by svarnau** [comment]
@mkby please review

**Comment by svarnau** [comment]
jenkins, retest

**Comment by svarnau** [comment]
Strange  that I got two very different failures, both unrelated to my changes. I have not seen either of these issues before.  
1) seabase/031 - an objectID did not get filtered in test output.
2) jdbc test cleanup failed to drop a table.
      BatchTest>JdbcCommon.doBaseTestCleanup:149->JdbcCommon.dropTestObjects:218 Failed to drop object: table BATCH_TEST_TABLE

All the test jobs have passed, just not all on the same run.

**Comment by arvind-narain** [comment]
Hi Steve - jdbc failure seems to be related to TRAFODION-2695 -  saw similar error in 
https://jenkins.esgyn.com/job/jdbc_test-cdh/2464/console. Will check with @selvaganesang  if they are related and if any testware modification is needed.

**Pull request merged**
