### PR TITLE
JIRA [TRAFODION-2236]

### PR DESCRIPTION
**Pull request by sbroeder**
TM crashes during startup

### CODE REVIEW

**Comment by shangshengtung** [comment]
Looks good.

**Comment by selvaganesang** [comment]
Looks good if there is no harm in dropping these zk nodes. Some explanation here why is it not harmful to delete these zk nodes would be helpful. Also, adding subject line to the PR request would help the reviewers when looking for what to review. He/she doesn't need to click to get the details and then decide to review.

**Comment by sbroeder** [comment]
This comment is taken from the JIRA - THis is safe to do because any region server needing recovery will repost to zookeeper and the TM will have no issues connecting to this RS.  My assumption is that all the discussion should be there, but I can duplicate it here.  I can add a more descriptive title for future PRs

**Comment by svarnau** [comment]
FYI, Pull-Request authors can edit title of the PR after the fact.

**Pull request merged**
