### PR TITLE
[TRAFODION-2326] TopN sort reuse of released tuples.

### PR DESCRIPTION
**Pull request by prashanth-vasudev**

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
jenkins, retest

**Comment by sureshsubbiah** [comment]
+1

**Comment by sureshsubbiah** [comment]
seabase/test033 seems to be crashing on a query rollup and firstN.

**Comment by prashanth-vasudev** [comment]
seabase/test033 use case is not getting handled. I am looking into fixing this. Will do another pull request.

**Pull request closed without merging**
