### PR TITLE
[TRAFODION-36] showddl does not show delimited names in ON subclause of SALT clause

### PR DESCRIPTION
**Pull request by anoopsharma00**
see JIRA for details.

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
jenkins, add user

**Comment by sureshsubbiah** [comment]
Thank you. Change looks good and can be merged after tests pass.

**Comment by DaveBirdsall** [comment]
Change looks good to me also.

**Comment by svarnau** [comment]
Well, jenkins is posting now, just not the right content.  Test results were:
https://jenkins02.trafodion.org/job/Check-PR/48/ (PASS)

**Pull request merged**
