### PR TITLE
fix regression test compGeneral TEST001

### PR DESCRIPTION
**Pull request by traflm**
Fix regression test case failure. 
Should be more carefully next time.

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
This is a follow-on for JIRA Trafodion 2047. I will commit it once tests pass.

**Comment by traflm** [comment]
to be safe, let me run extra test, and check the result of compGeneral TEST001

**Comment by traflm** [comment]
Jenkins, extra tests

**Comment by DaveBirdsall** [comment]
My bad; I already committed it. I should have looked to see if compGeneral was included in the original Jenkins tests. This means you'll need to submit yet another pull request if this change was not satisfactory.

**Comment by traflm** [comment]
I run the test before submit, so it should work. Let me git pull and test again.

**Pull request merged**
