### PR TITLE
TRAFODION-1846

### PR DESCRIPTION
**Pull request by mashengchen**
add traf_coprocessor.properties to all node .

### CODE REVIEW

**Comment by traflm** [comment]
Looks good for me. Thanks for fix this issue.

**Comment by DaveBirdsall** [comment]
Looks good to me too.

**Comment by traflm** [comment]
Not very good at GIT, why I saw 4 commits in this pull request?
Hope it is not an issue. Only one file changed, I hope this is my over concern :-)

**Comment by DaveBirdsall** [comment]
Ming: It looks like what happened is Aven developed her work on her master branch, and the first few commits are merges from the origin/master branch to bring it up-to-date. (You can look at these by clicking on the SHA code -- the 7-digit hex code -- given at the right of the commits.) The final result is just the one file change. I think all is well. 

Another way to develop code that doesn't require such merge commits is to create a fresh branch each time that tracks origin/master, and then discard that branch after the pull request is merged. That's the way recommended in the Trafodion Contributor's Guide.

**Pull request merged**
