### PR TITLE
[TRAFODION-18] alter column datatype support.

### PR DESCRIPTION
**Pull request by anoopsharma00**
Support for item #4 in jira.
Syntax:  alter table <t> alter column <a>  <new_datatype>;
 Following conditions need to be met for alter to work:
      -- old and new column datatype must be VARCHAR (variable length string datatype)
      -- new col length must be greater than or equal to old length
      -- old and new character sets must be the same
      -- altered columns cannot be part of primary key or secondary index key
      -- table cannot be a volatile table.
An error (1404) will be returned if these conditions are not met.

### CODE REVIEW

**Comment by sandhyasun** [comment]
jenkins, add user

**Comment by amandamoran** [comment]
jenkins, add user

**Comment by svarnau** [comment]
jenkins, retest

**Comment by svarnau** [comment]
jenkins, retest -- trying again

**Comment by svarnau** [comment]
jenkins, retest -- yet again

**Comment by anoopsharma00** [comment]
regression test seabase/TEST011 has new tests for this change. 

Not sure if regressions have been run yet during jenkins build.

**Comment by svarnau** [comment]
jenkins, add user

**Comment by sandhyasun** [comment]
jenkins, retest

**Comment by sandhyasun** [comment]
Looks good ! Merging it in now...

**Pull request merged**
