### PR TITLE
[TRAFODION-2820] Correct some mistakes (hp) in *Trafodion JDBC Type 4 Programmer’s Reference Guide*

### PR DESCRIPTION
**Pull request by liuyu000**

### CODE REVIEW

**Comment by liuyu000** [comment]
@DaveBirdsall Sure, I've fixed.
By the way, these two chapters (**Working with BLOB and CLOB Data** and **Managing the SQL Tables for BLOB and CLOB Data**) are not visible on the website: [http://trafodion.incubator.apache.org/docs/jdbct4ref_guide/index.html](url), could you please help rebuild the website? Many thanks!

**Comment by DaveBirdsall** [comment]
@liuyu000, I partially figured out why the two chapters are not visible. Their entries in incubator-trafodion/docs/jdbct4ref_guide/src/asciidoc/index.adoc are commented out. Evidently when this manual was first published (on April 29, 2016) those chapters were intentially left out. I'm wondering if perhaps LOB support was not yet ready in the JDBC T4 code?

Perhaps we can check with a JDBC T4 developer to ask what the status of LOB support is? Perhaps @sandhyasun knows something about that?

If the LOB support is ready, a simple change to index.adoc will include the chapters.

**Comment by DaveBirdsall** [comment]
Even without the LOB chapters. I think this change is ready to merge as-is. I'll wait a day, though, in case you decide to include the LOB chapters as well.

**Comment by DaveBirdsall** [comment]
I went ahead and merged this change and rebuilt the web site. The LOB chapters can remain invisible for a while; it appears they are not ready. See this e-mail thread on the Trafodion dev list: http://mail-archives.apache.org/mod_mbox/incubator-trafodion-dev/201711.mbox/%3CMWHPR10MB161364FF25ADF87EB277A102E4380%40MWHPR10MB1613.namprd10.prod.outlook.com%3E

**Pull request merged**
