### PR TITLE
[TRAFODION - 1607] - Missing version for jdbcT2 and jdbcT4 jar files

### PR DESCRIPTION
**Pull request by hegdean**

### CODE REVIEW

**Comment by arvind-narain** [comment]
Looks ok to me. One extra file (install_traf_components) - maybe because of rebase ?

**Comment by sureshsubbiah** [comment]
Is this change ready to be merged? I will do so in a few hours unless there there are new comments. The change in install_traf_components seems harmless (an extra blank line)

**Comment by hegdean** [comment]
not yet Suresh.  I need to run tests before I can commit additional changes

**Comment by sureshsubbiah** [comment]
Change looks good to me.

**Comment by arvind-narain** [comment]
Changes look good. Do you want to revert the changes in .gitignore and Makefile ?

**Comment by arvind-narain** [comment]
Thanks for the change - merging now.

**Pull request merged**
