### PR TITLE
[TRAFODION-1776] Reduce web-site build steps

### PR DESCRIPTION
**Pull request by svarnau**
Added child modules to top-level POM file to build each document.

Must use "mvn post-site" command, so that all docs get copied into
website docs directory.

Updated documentation on building docs and website.

Updated documents (except for install_guide, since it is still in
development) to use the current Trafodion release version.
This requires sourcing the env.sh file before building docs.

### CODE REVIEW

**Comment by svarnau** [comment]
jenkins, retest -- jenkins script was not properly updated to source env.sh for docs build

**Comment by svarnau** [comment]
jenkins, retest -- trafodion env requires bash shell

**Comment by svarnau** [comment]
Tests revealed an issue.  Some compile-time dependencies are causing failure for site phase of building the docs.  Will need some re-work.  More to come.

**Comment by DaveBirdsall** [comment]
Is there any overlap between the document changes in this change and the work Gunnar is doing to put contributor procedures into a document?

**Comment by svarnau** [comment]
@DaveBirdsall, yes Gunnar will need to pick up these changes to the two markdown files I changed when he migrates them to asciidoc.

**Comment by gtapper** [comment]
How do you build the documents in Eclipse on a PC if having to source env.sh? To date, it's been possible to work on documentation and website purely on Windows without having to set up a Trafodion Build Environment. Hopefully, this is just a matter of instructions.

**Comment by svarnau** [comment]
@gtapper - It must be possible to set an environment variable in eclipse.  You don't necessarily have to source env.sh, but you at least have to set TRAFODION_VER in the environment.

**Comment by venkat1m** [comment]
In a Run configuration in eclipse, you can use the Environment tab to set any environment variables. You can also use different Maven profiles for eclipse and command line builds and choose to set the TRAFODION_VER differently for eclipse build.

**Comment by DaveBirdsall** [comment]
Is this ready to commit?

**Pull request merged**
