### PR TITLE
[[Trafodion-1218]] Fix new hosts names, adding a node to instatllation, and cloudera bug

### PR DESCRIPTION
**Pull request by amandamoran**

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
All looks good to me.

**Comment by amandamoran** [comment]
Thanks Dave! Could a committer please commit this change?

THANK YOU!

On Mon, Aug 24, 2015 at 10:56 AM, DaveBirdsall <notifications@github.com>
wrote:

> All looks good to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/64#issuecomment-134317095>
> .
>



-- 
Thanks,

Amanda Moran

**Comment by DaveBirdsall** [comment]
Done. By the way, you're a committer too, right? It's OK for you to commit your own change. (But I'm glad to do it.)

**Comment by amandamoran** [comment]
Great! Good to know!

Thanks!

On Tue, Aug 25, 2015 at 8:43 AM, DaveBirdsall <notifications@github.com>
wrote:

> Done. By the way, you're a committer too, right? It's OK for you to commit
> your own change. (But I'm glad to do it.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-trafodion/pull/64#issuecomment-134635459>
> .
>



-- 
Thanks,

Amanda Moran

**Pull request merged**
