### PR TITLE
Change release version from 1.3 to 2.0

### PR DESCRIPTION
**Pull request by svarnau**
The release1.3 branch is created. This will now distinguish the master
branch as preparing for 2.0 release.

### CODE REVIEW

**Comment by DaveBirdsall** [comment]
Changes look good. Question: Where does the version number in the sqlci banner come from? Will these changes effect that one also?

**Comment by svarnau** [comment]
@DaveBirdsall - I believe the sqlci banner version comes from the setting in sqenvcom.sh.

**Comment by svarnau** [comment]
@DaveBirdsall - We can see that it is updated in the test logs: http://traf-logs.esgyn.com/PullReq/151/78/regress-core-hdp/sql-regress-logs/Regress.log 

Apache Trafodion Conversational Interface 2.0.0

**Comment by DaveBirdsall** [comment]
Thanks, @svarnau. It all looks good.

**Pull request merged**
