### PR TITLE
TRAFODION-2067 support cdh5.7 & hbase1.2

### PR DESCRIPTION
**Pull request by mashengchen**
previous PR #610  has some conflict.  do a new PR
1. support cdh5.7 & hbase1.2. add hbase-trx-cdh5.7.jar & hbase-trx-apache1.2.jar

2. HBASE_DISTRO add CDH5.7 APACHE1.2

3. remove cdh & apache & cdh version in trafodion-dtm-.jar & trafodion-sql-.jar & trafodion-utility-.jar, they will be trafodion-dtm-[apache][cdh][hdp]-$trafodion_version.jar & trafodion-sql-[apache][cdh][hdp]-$trafodion_version.jar & trafodion-utility-$trafodion_version.jar . becacuse we can't determine which version user will install. and we only have one version of each jar. but not hbase-trx.jar, so hbase-trx*.jar have version, because they have multi version. eg: for cdh they have hbase-trx-cdh5_4-2.1.0.jar & hbase-trx-cdh5_5-2.1.0.jar & hbase-trx-cdh5_7-2.1.0.jar

4. HBASE1.* ->APACHE1.* in .tmpl files.

5. do some optimize in traf_config_check

### CODE REVIEW

**Comment by traflm** [comment]
jenkins, retest

**Comment by mashengchen** [comment]
some changes in #625 result in the test can't pass , i will change it .

**Comment by prashanth-vasudev** [comment]
Looks good to me. Thanks.

**Comment by sureshsubbiah** [comment]
+1. Merging based on Prashanth's review here and previous reviews by Amanda, Prashanth and others.

**Pull request merged**
