### PR TITLE
support vanilla hbase 0.98.10

### PR DESCRIPTION
**Pull request by mashengchen**
change getFamilyMap() to getFamilyCellMap()
add ScanQueryMatcher instantiation for hbase 0.98.9 and later version
change ScanInfo instantiation for hbase 0.98.8 and later version

### CODE REVIEW

**Comment by sureshsubbiah** [comment]
jenkins, add user

**Comment by zellerh** [comment]
Thank you, that is wonderful to have! The code looks good to me, but I didn't validate all the details, hope someone with more HBase-trx expertise can have a look. I also hope that this solution will port well to HBase 1.0.

I am wondering whether we still need to build four different jar files for HBase-trx, given that we use Java reflection to figure out which interfaces to use. That's a general question, not directly related to this change.

**Comment by mashengchen** [comment]
jenkins, retest

**Comment by mashengchen** [comment]
jenkins, retest

**Comment by sbroeder** [comment]
Looks Good Aven - Sean

**Comment by DaveBirdsall** [comment]
I am attempting to commit this but am running into git difficulties that I don't understand. (In my workspace, it showed conflicts in some of the files, which I resolved. But it also shows file additions and deletions for files that don't seem to be connected to this pull request.) I don't want to commit it until I understand what is going on. And I'll need some help for that. I will try to resolve this tomorrow. 

Another possibility is to close this pull request, and submit a fresh one with just the intended changes. 

I'm very sorry this is taking so long.

**Comment by DaveBirdsall** [comment]
With Steve Varnau's help, I now know why my efforts were failing. I was trying to merge this into the wrong branch! Good thing I didn't complete it.

**Comment by DaveBirdsall** [comment]
I'm committing this to the apache/release1.3 branch now.

**Pull request merged**
