### PR TITLE
fix regression test hive 005

### PR DESCRIPTION
**Pull request by traflm**
fix regression test HIVE test005
the expected file is missing a empty line.

Also fix an issue in sqstart when 'ulimit -l' is unlimited, thanks @ryzuo to detect this issue.

### CODE REVIEW

**Comment by traflm** [comment]
Jenkins, extra tests

**Comment by selvaganesang** [comment]
Looks good

**Comment by DaveBirdsall** [comment]
Looks good to me.

**Comment by sureshsubbiah** [comment]
+1

**Pull request merged**
