### PR TITLE
Removing hardcoding of Apache version

### PR DESCRIPTION
**Pull request by amandamoran**

### CODE REVIEW

**Comment by svarnau** [comment]
Looks good to me.

**Comment by svarnau** [comment]
I've verified this fix against 2.1 version on master branch. (This was the problem version that prompted this change.)

**Comment by DaveBirdsall** [comment]
Is this change ready to be merged into apache:master?

**Comment by svarnau** [comment]
Amanda is on vacation, but Yes, I think it is ready.

**Pull request merged**
